// ─── NourishIQ Recipe Collection ────────────────────────────────────────────
// Goal-aligned recipes with estimated macros per serving.
// ─────────────────────────────────────────────────────────────────────────────

import type { Recipe } from "./types";

export const RECIPES: Recipe[] = [
  {
    id: "chicken_quinoa_bowl",
    name: "Grilled Chicken & Quinoa Bowl",
    emoji: "🍗",
    meal: ["lunch", "dinner"],
    kcal: 480, protein: 42, carbs: 45, fat: 12, fiber: 8, gi: 50,
    glutenFree: true, diet: "nonveg", timeMin: 30,
    goals: ["muscle_gain", "weight_loss", "visceral_fat", "protein_rich"],
    hue: "bg-[#E4F6EE]",
    ingredients: [
      "150 g chicken breast, skinless",
      "120 g cooked quinoa (½ katori uncooked)",
      "1 cup broccoli + capsicum, chopped",
      "2 tsp olive oil, ½ lemon, black pepper",
      "Pink salt, garlic, mixed herbs",
    ],
    steps: [
      "Marinate chicken in lemon, garlic, herbs & 1 tsp oil for 15 min.",
      "Grill 6–7 min per side until juices run clear; rest 5 min, slice.",
      "Sauté broccoli & capsicum in remaining oil, 3–4 min (keep crunchy).",
      "Assemble: quinoa base → veggies → chicken. Season and serve warm.",
    ],
    tip: "Resting the chicken after cooking keeps it juicy — cutting early loses moisture.",
  },
  {
    id: "paneer_tikka",
    name: "Oven Paneer Tikka + Mint Chutney",
    emoji: "🧈",
    meal: ["snack", "dinner"],
    kcal: 320, protein: 22, carbs: 12, fat: 20, fiber: 4, gi: 15,
    glutenFree: true, diet: "vegetarian", timeMin: 25,
    goals: ["muscle_gain", "protein_rich", "visceral_fat", "optimal_health"],
    hue: "bg-[#F3EAF8]",
    ingredients: [
      "150 g paneer, 2 cm cubes",
      "3 tbsp thick curd (hung)",
      "1 tsp tandoori masala, ¼ tsp turmeric, red chilli",
      "Onion & capsicum petals, lemon",
      "Mint-coriander chutney to serve",
    ],
    steps: [
      "Whisk curd + spices into a thick marinade.",
      "Coat paneer and veggies; rest 20 min (or 2 h for deeper flavour).",
      "Skewer and bake at 200°C for 15–18 min, turning once.",
      "Char 2 min on tawa/stove flame for smokiness. Serve with chutney.",
    ],
    tip: "Hung curd clings better than watery curd — drain 15 minutes in a muslin cloth.",
  },
  {
    id: "moong_chilla",
    name: "Moong Dal Chilla (2) with Chutney",
    emoji: "🥞",
    meal: ["breakfast"],
    kcal: 280, protein: 16, carbs: 34, fat: 8, fiber: 7, gi: 45,
    glutenFree: true, diet: "vegetarian", timeMin: 20,
    goals: ["weight_loss", "visceral_fat", "protein_rich", "optimal_health"],
    hue: "bg-[#EAF4E2]",
    ingredients: [
      "60 g yellow moong dal, soaked 3–4 h",
      "1 green chilli, ginger, coriander",
      "¼ tsp hing, salt, 1 tsp oil",
      "Grated carrot/onion for stuffing (optional)",
    ],
    steps: [
      "Drain dal; blend with chilli, ginger & ¼ cup water into a smooth batter.",
      "Stir in salt, hing, coriander, chopped veggies.",
      "Spread 2 chillas on a hot non-stick tawa with a few drops of oil.",
      "Cook 2–3 min per side till golden. Serve with green chutney.",
    ],
    tip: "Thin batter = crisp chilla; thick = soft. Adjust with water one spoon at a time.",
  },
  {
    id: "ragi_dosa",
    name: "Ragi Dosa + Sambar",
    emoji: "🌾",
    meal: ["breakfast", "dinner"],
    kcal: 340, protein: 11, carbs: 52, fat: 8, fiber: 9, gi: 52,
    glutenFree: true, diet: "vegetarian", timeMin: 25,
    goals: ["weight_loss", "visceral_fat", "optimal_health"],
    hue: "bg-[#E4F6EE]",
    ingredients: [
      "40 g ragi flour, 20 g rice flour",
      "2 tbsp curd, cumin, green chilli, curry leaves",
      "Salt, 1 tsp oil",
      "1 katori sambar (toor dal + veggies)",
    ],
    steps: [
      "Whisk flours, curd, salt + 1.5 cups water into a thin batter; rest 15 min.",
      "Season with cumin, chilli and curry leaves.",
      "Pour thin dosas on a hot tawa, drizzle oil, cook 2–3 min per side.",
      "Serve hot with sambar and a spoon of coconut chutney.",
    ],
    tip: "No fermentation needed — this instant-batter version keeps mornings fast.",
  },
  {
    id: "yogurt_berry_bowl",
    name: "Greek Yogurt Berry Bowl with Chia",
    emoji: "🫐",
    meal: ["breakfast", "snack"],
    kcal: 300, protein: 24, carbs: 30, fat: 9, fiber: 7, gi: 35,
    glutenFree: true, diet: "vegetarian", timeMin: 5,
    goals: ["muscle_gain", "weight_loss", "protein_rich", "optimal_health"],
    hue: "bg-[#F3EAF8]",
    ingredients: [
      "200 g plain Greek yogurt",
      "¾ cup mixed berries or 1 chopped guava",
      "1 tbsp chia seeds",
      "8 chopped almonds",
      "1 tsp honey (optional)",
    ],
    steps: [
      "Spoon yogurt into a bowl.",
      "Top with fruit, chia and almonds.",
      "Drizzle honey only if needed — berries bring natural sweetness.",
      "Let chia hydrate 5 min before eating.",
    ],
    tip: "24 g of protein before 10 am is the easiest way to hit a high-protein day.",
  },
  {
    id: "rajma_rice",
    name: "Rajma with Brown Rice & Salad",
    emoji: "🍛",
    meal: ["lunch"],
    kcal: 450, protein: 16, carbs: 72, fat: 8, fiber: 13, gi: 55,
    glutenFree: true, diet: "vegan", timeMin: 45,
    goals: ["optimal_health", "weight_gain", "weight_loss"],
    hue: "bg-[#EAF4E2]",
    ingredients: [
      "60 g dry rajma (soaked overnight)",
      "80 g cooked brown rice",
      "Onion-tomato masala, ginger-garlic",
      "1 tsp mustard oil, garam masala",
      "Cucumber-onion salad with lemon",
    ],
    steps: [
      "Pressure-cook soaked rajma with salt till soft (4–5 whistles).",
      "Build masala: onion → tomato → spices; add rajma with cooking water.",
      "Simmer 15 min till gravy thickens.",
      "Plate rice + rajma + salad; finish with lemon and raw onion.",
    ],
    tip: "The classic carb+legume pairing = complete amino-acid profile at low cost.",
  },
  {
    id: "salmon_greens",
    name: "Pan-Seared Salmon & Sautéed Greens",
    emoji: "🐟",
    meal: ["dinner"],
    kcal: 430, protein: 36, carbs: 10, fat: 26, fiber: 4, gi: 15,
    glutenFree: true, diet: "nonveg", timeMin: 20,
    goals: ["visceral_fat", "optimal_health", "protein_rich"],
    hue: "bg-[#FCEFD9]",
    ingredients: [
      "130 g salmon fillet",
      "2 cups spinach + green beans",
      "2 tsp olive oil, 2 garlic cloves",
      "Lemon, black pepper, salt",
    ],
    steps: [
      "Pat salmon dry; season. Sear skin-side down 4 min in hot oil.",
      "Flip, cook 3 min more; rest on a plate.",
      "Sauté garlic, then greens 2 min till just wilted.",
      "Plate with lemon squeeze and pepper.",
    ],
    tip: "Crispy skin = dry skin. Don't move the fillet for the first 4 minutes.",
  },
  {
    id: "tofu_stirfry",
    name: "Tofu-Veg Stir-fry with Foxtail Millet",
    emoji: "🌱",
    meal: ["lunch", "dinner"],
    kcal: 420, protein: 24, carbs: 46, fat: 14, fiber: 8, gi: 50,
    glutenFree: true, diet: "vegan", timeMin: 30,
    goals: ["weight_loss", "visceral_fat", "muscle_gain", "optimal_health"],
    hue: "bg-[#EAF4E2]",
    ingredients: [
      "150 g firm tofu, pressed & cubed",
      "120 g cooked foxtail millet",
      "1.5 cups mixed veg (beans, carrot, capsicum)",
      "1 tsp sesame oil, ginger, chilli, soy (use tamari if GF-strict)",
      "Sesame seeds to garnish",
    ],
    steps: [
      "Press tofu 10 min; pan-sear cubes till golden, set aside.",
      "Stir-fry veggies on high heat 3–4 min (crisp-tender).",
      "Add tofu, ginger & tamari; toss 1 min.",
      "Serve over warm millet, garnish with sesame.",
    ],
    tip: "Pressing tofu removes water — this is the difference between soggy and golden.",
  },
  {
    id: "egg_toast",
    name: "Veg Egg-White Omelette + Multigrain Toast",
    emoji: "🍳",
    meal: ["breakfast"],
    kcal: 320, protein: 26, carbs: 22, fat: 12, fiber: 5, gi: 50,
    glutenFree: false, diet: "egg", timeMin: 15,
    goals: ["muscle_gain", "weight_loss", "protein_rich"],
    hue: "bg-[#FBF3E2]",
    ingredients: [
      "1 whole egg + 3 whites",
      "Onion, tomato, spinach, chilli (¼ cup)",
      "2 slices multigrain bread",
      "1 tsp oil/ghee, salt, pepper",
    ],
    steps: [
      "Beat eggs with veggies, salt & pepper.",
      "Cook covered on low heat 4–5 min till set; fold.",
      "Toast bread while the omelette sets.",
      "Serve stacked with black coffee or chai (less sugar).",
    ],
    tip: "One whole egg + extra whites gives yolk nutrients with maximum protein.",
  },
  {
    id: "palak_paneer_bajra",
    name: "Palak Paneer + Bajra Roti",
    emoji: "🥬",
    meal: ["lunch", "dinner"],
    kcal: 440, protein: 20, carbs: 38, fat: 22, fiber: 10, gi: 50,
    glutenFree: true, diet: "vegetarian", timeMin: 35,
    goals: ["visceral_fat", "protein_rich", "optimal_health"],
    hue: "bg-[#E4F6EE]",
    ingredients: [
      "100 g paneer cubes",
      "2 cups blanched spinach purée",
      "Onion, tomato, ginger-garlic, 1 tsp ghee",
      "1 bajra roti (40 g flour)",
      "Salt, chilli, garam masala",
    ],
    steps: [
      "Blanch spinach 2 min, shock in cold water, blend smooth.",
      "Sauté onion-tomato in ghee; add spices.",
      "Add purée + paneer; simmer 5 min. Don't overcook — keep it green.",
      "Serve with hot bajra roti and a spoon of curd.",
    ],
    tip: "Blanching + cold shock keeps the palak emerald green instead of olive-brown.",
  },
  {
    id: "chicken_soup",
    name: "Clear Chicken-Veg Soup",
    emoji: "🍲",
    meal: ["snack", "dinner"],
    kcal: 150, protein: 18, carbs: 8, fat: 4, fiber: 2, gi: 15,
    glutenFree: true, diet: "nonveg", timeMin: 25,
    goals: ["weight_loss", "visceral_fat", "protein_rich"],
    hue: "bg-[#FCEFD9]",
    ingredients: [
      "100 g chicken breast, minced/shredded",
      "2 cups clear broth or water",
      "Carrot, beans, cabbage (½ cup)",
      "Ginger, garlic, black pepper, vinegar ½ tsp",
    ],
    steps: [
      "Simmer ginger-garlic in broth 5 min.",
      "Add chicken; poach 8–10 min, skim foam.",
      "Add veggies; cook 4 min.",
      "Season with pepper & vinegar; serve hot.",
    ],
    tip: "A hot protein soup before dinner measurably reduces how much you eat after.",
  },
  {
    id: "sprout_chaat",
    name: "Moong Sprout Chaat",
    emoji: "🌱",
    meal: ["snack", "breakfast"],
    kcal: 180, protein: 11, carbs: 26, fat: 3, fiber: 8, gi: 30,
    glutenFree: true, diet: "vegan", timeMin: 15,
    goals: ["weight_loss", "visceral_fat", "optimal_health"],
    hue: "bg-[#EAF4E2]",
    ingredients: [
      "1 cup moong sprouts (steamed 3 min)",
      "Onion, tomato, cucumber, coriander",
      "Lemon, chaat masala, pinch of salt",
      "1 tbsp peanuts (optional crunch)",
    ],
    steps: [
      "Lightly steam sprouts (keeps them digestible).",
      "Toss with chopped veggies, spices, lemon.",
      "Add peanuts for staying power.",
      "Eat fresh — sprouts dry out fast.",
    ],
    tip: "Raw sprouts can harbor bacteria; a 3-minute steam makes them safe without killing nutrients.",
  },
  {
    id: "overnight_oats",
    name: "Overnight Oats with Whey & Almonds",
    emoji: "🥣",
    meal: ["breakfast"],
    kcal: 380, protein: 30, carbs: 38, fat: 10, fiber: 6, gi: 50,
    glutenFree: true, diet: "vegetarian", timeMin: 5,
    goals: ["muscle_gain", "protein_rich", "weight_loss"],
    hue: "bg-[#FBF3E2]",
    ingredients: [
      "40 g rolled oats (certified GF if needed)",
      "1 scoop (~30 g) vanilla whey or plant protein",
      "150 ml milk or soy milk",
      "1 tbsp chia, 8 almonds, cinnamon",
      "½ banana, sliced",
    ],
    steps: [
      "Mix oats, chia, cinnamon, milk; refrigerate overnight.",
      "In the morning stir in protein powder (add a splash of milk if thick).",
      "Top with banana and almonds.",
      "Grab and go — zero morning cooking.",
    ],
    tip: "Stir whey in the morning, not the night before — it keeps the texture silky.",
  },
  {
    id: "millet_khichdi",
    name: "Veg Millet Khichdi",
    emoji: "🍛",
    meal: ["lunch", "dinner"],
    kcal: 350, protein: 12, carbs: 54, fat: 9, fiber: 9, gi: 52,
    glutenFree: true, diet: "vegan", timeMin: 30,
    goals: ["weight_loss", "optimal_health", "visceral_fat"],
    hue: "bg-[#E4F6EE]",
    ingredients: [
      "50 g foxtail/little millet",
      "30 g moong dal",
      "1 cup mixed veg (peas, carrot, beans)",
      "1 tsp ghee/oil, cumin, hing, turmeric",
      "Salt, ginger",
    ],
    steps: [
      "Rinse millet + dal; soak 15 min.",
      "Temper cumin, hing, ginger in ghee; add veggies & turmeric.",
      "Add millet, dal, salt + 2 cups water; pressure-cook 3 whistles.",
      "Rest, fluff, serve with curd or kadhi.",
    ],
    tip: "The millet-dal combo covers amino acids that each lacks — ancient food science.",
  },
  {
    id: "pb_smoothie",
    name: "Peanut Butter Banana Smoothie",
    emoji: "🥤",
    meal: ["breakfast", "snack"],
    kcal: 350, protein: 18, carbs: 40, fat: 13, fiber: 5, gi: 45,
    glutenFree: true, diet: "vegetarian", timeMin: 5,
    goals: ["weight_gain", "muscle_gain", "protein_rich"],
    hue: "bg-[#FBF3E2]",
    ingredients: [
      "250 ml full-fat milk or soy milk",
      "1 banana",
      "2 tbsp natural peanut butter",
      "1 scoop protein powder (optional → +18 g protein)",
      "2 ice cubes, cinnamon",
    ],
    steps: [
      "Blend everything 45–60 sec till frothy.",
      "Taste; adjust thickness with milk.",
      "Pour, dust with cinnamon.",
      "Post-workout or as a weight-gain snack between meals.",
    ],
    tip: "The easiest 350+ healthy calories for hard-gainers who struggle to eat enough.",
  },
  {
    id: "fish_curry_rice",
    name: "Light Fish Curry + Red Rice",
    emoji: "🐟",
    meal: ["lunch", "dinner"],
    kcal: 460, protein: 32, carbs: 48, fat: 14, fiber: 4, gi: 55,
    glutenFree: true, diet: "nonveg", timeMin: 35,
    goals: ["optimal_health", "protein_rich", "visceral_fat"],
    hue: "bg-[#FCEFD9]",
    ingredients: [
      "150 g firm fish (bangda/rohu), cubed",
      "Onion-tomato-coconut masala (2 tbsp grated coconut)",
      "Turmeric, chilli, coriander powder",
      "1 tsp mustard oil, curry leaves",
      "100 g cooked red/brown rice",
    ],
    steps: [
      "Marinate fish in turmeric + salt 10 min.",
      "Sauté onion, tomato, curry leaves; grind coconut in if using.",
      "Simmer gravy 8 min; slip in fish; cook 6–7 min gently.",
      "Serve with red rice and steamed veggies.",
    ],
    tip: "Never boil fish hard — it breaks. A gentle simmer keeps pieces whole.",
  },
];
