// ─── NourishIQ Recipe Collection ────────────────────────────────────────────
// Goal-aligned recipes with estimated macros per serving.
// ─────────────────────────────────────────────────────────────────────────────

import type { Recipe } from "./types";

export const RECIPES: Recipe[] = [
  {
    id: "chicken_quinoa_bowl",
    name: "Grilled Chicken & Quinoa Bowl",
    emoji: "🍗",
    meal: ["lunch", "dinner"],
    kcal: 480, protein: 42, carbs: 45, fat: 12, fiber: 8, gi: 50,
    glutenFree: true, diet: "nonveg", timeMin: 30,
    goals: ["muscle_gain", "weight_loss", "visceral_fat", "protein_rich"],
    hue: "bg-[#E4F6EE]",
    ingredients: [
      "150 g chicken breast, skinless",
      "120 g cooked quinoa (½ katori uncooked)",
      "1 cup broccoli + capsicum, chopped",
      "2 tsp olive oil, ½ lemon, black pepper",
      "Pink salt, garlic, mixed herbs",
    ],
    steps: [
      "Marinate chicken in lemon, garlic, herbs & 1 tsp oil for 15 min.",
      "Grill 6–7 min per side until juices run clear; rest 5 min, slice.",
      "Sauté broccoli & capsicum in remaining oil, 3–4 min (keep crunchy).",
      "Assemble: quinoa base → veggies → chicken. Season and serve warm.",
    ],
    tip: "Resting the chicken after cooking keeps it juicy — cutting early loses moisture.",
  },
  {
    id: "paneer_tikka",
    name: "Oven Paneer Tikka + Mint Chutney",
    emoji: "🧈",
    meal: ["snack", "dinner"],
    kcal: 320, protein: 22, carbs: 12, fat: 20, fiber: 4, gi: 15,
    glutenFree: true, diet: "vegetarian", timeMin: 25,
    goals: ["muscle_gain", "protein_rich", "visceral_fat", "optimal_health"],
    hue: "bg-[#F3EAF8]",
    ingredients: [
      "150 g paneer, 2 cm cubes",
      "3 tbsp thick curd (hung)",
      "1 tsp tandoori masala, ¼ tsp turmeric, red chilli",
      "Onion & capsicum petals, lemon",
      "Mint-coriander chutney to serve",
    ],
    steps: [
      "Whisk curd + spices into a thick marinade.",
      "Coat paneer and veggies; rest 20 min (or 2 h for deeper flavour).",
      "Skewer and bake at 200°C for 15–18 min, turning once.",
      "Char 2 min on tawa/stove flame for smokiness. Serve with chutney.",
    ],
    tip: "Hung curd clings better than watery curd — drain 15 minutes in a muslin cloth.",
  },
  {
    id: "moong_chilla",
    name: "Moong Dal Chilla (2) with Chutney",
    emoji: "🥞",
    meal: ["breakfast"],
    kcal: 280, protein: 16, carbs: 34, fat: 8, fiber: 7, gi: 45,
    glutenFree: true, diet: "vegetarian", timeMin: 20,
    goals: ["weight_loss", "visceral_fat", "protein_rich", "optimal_health"],
    hue: "bg-[#EAF4E2]",
    ingredients: [
      "60 g yellow moong dal, soaked 3–4 h",
      "1 green chilli, ginger, coriander",
      "¼ tsp hing, salt, 1 tsp oil",
      "Grated carrot/onion for stuffing (optional)",
    ],
    steps: [
      "Drain dal; blend with chilli, ginger & ¼ cup water into a smooth batter.",
      "Stir in salt, hing, coriander, chopped veggies.",
      "Spread 2 chillas on a hot non-stick tawa with a few drops of oil.",
      "Cook 2–3 min per side till golden. Serve with green chutney.",
    ],
    tip: "Thin batter = crisp chilla; thick = soft. Adjust with water one spoon at a time.",
  },
  {
    id: "ragi_dosa",
    name: "Ragi Dosa + Sambar",
    emoji: "🌾",
    meal: ["breakfast", "dinner"],
    kcal: 340, protein: 11, carbs: 52, fat: 8, fiber: 9, gi: 52,
    glutenFree: true, diet: "vegetarian", timeMin: 25,
    goals: ["weight_loss", "visceral_fat", "optimal_health"],
    hue: "bg-[#E4F6EE]",
    ingredients: [
      "40 g ragi flour, 20 g rice flour",
      "2 tbsp curd, cumin, green chilli, curry leaves",
      "Salt, 1 tsp oil",
      "1 katori sambar (toor dal + veggies)",
    ],
    steps: [
      "Whisk flours, curd, salt + 1.5 cups water into a thin batter; rest 15 min.",
      "Season with cumin, chilli and curry leaves.",
      "Pour thin dosas on a hot tawa, drizzle oil, cook 2–3 min per side.",
      "Serve hot with sambar and a spoon of coconut chutney.",
    ],
    tip: "No fermentation needed — this instant-batter version keeps mornings fast.",
  },
  {
    id: "yogurt_berry_bowl",
    name: "Greek Yogurt Berry Bowl with Chia",
    emoji: "🫐",
    meal: ["breakfast", "snack"],
    kcal: 300, protein: 24, carbs: 30, fat: 9, fiber: 7, gi: 35,
    glutenFree: true, diet: "vegetarian", timeMin: 5,
    goals: ["muscle_gain", "weight_loss", "protein_rich", "optimal_health"],
    hue: "bg-[#F3EAF8]",
    ingredients: [
      "200 g plain Greek yogurt",
      "¾ cup mixed berries or 1 chopped guava",
      "1 tbsp chia seeds",
      "8 chopped almonds",
      "1 tsp honey (optional)",
    ],
    steps: [
      "Spoon yogurt into a bowl.",
      "Top with fruit, chia and almonds.",
      "Drizzle honey only if needed — berries bring natural sweetness.",
      "Let chia hydrate 5 min before eating.",
    ],
    tip: "24 g of protein before 10 am is the easiest way to hit a high-protein day.",
  },
  {
    id: "rajma_rice",
    name: "Rajma with Brown Rice & Salad",
    emoji: "🍛",
    meal: ["lunch"],
    kcal: 450, protein: 16, carbs: 72, fat: 8, fiber: 13, gi: 55,
    glutenFree: true, diet: "vegan", timeMin: 45,
    goals: ["optimal_health", "weight_gain", "weight_loss"],
    hue: "bg-[#EAF4E2]",
    ingredients: [
      "60 g dry rajma (soaked overnight)",
      "80 g cooked brown rice",
      "Onion-tomato masala, ginger-garlic",
      "1 tsp mustard oil, garam masala",
      "Cucumber-onion salad with lemon",
    ],
    steps: [
      "Pressure-cook soaked rajma with salt till soft (4–5 whistles).",
      "Build masala: onion → tomato → spices; add rajma with cooking water.",
      "Simmer 15 min till gravy thickens.",
      "Plate rice + rajma + salad; finish with lemon and raw onion.",
    ],
    tip: "The classic carb+legume pairing = complete amino-acid profile at low cost.",
  },
  {
    id: "salmon_greens",
    name: "Pan-Seared Salmon & Sautéed Greens",
    emoji: "🐟",
    meal: ["dinner"],
    kcal: 430, protein: 36, carbs: 10, fat: 26, fiber: 4, gi: 15,
    glutenFree: true, diet: "nonveg", timeMin: 20,
    goals: ["visceral_fat", "optimal_health", "protein_rich"],
    hue: "bg-[#FCEFD9]",
    ingredients: [
      "130 g salmon fillet",
      "2 cups spinach + green beans",
      "2 tsp olive oil, 2 garlic cloves",
      "Lemon, black pepper, salt",
    ],
    steps: [
      "Pat salmon dry; season. Sear skin-side down 4 min in hot oil.",
      "Flip, cook 3 min more; rest on a plate.",
      "Sauté garlic, then greens 2 min till just wilted.",
      "Plate with lemon squeeze and pepper.",
    ],
    tip: "Crispy skin = dry skin. Don't move the fillet for the first 4 minutes.",
  },
  {
    id: "tofu_stirfry",
    name: "Tofu-Veg Stir-fry with Foxtail Millet",
    emoji: "🌱",
    meal: ["lunch", "dinner"],
    kcal: 420, protein: 24, carbs: 46, fat: 14, fiber: 8, gi: 50,
    glutenFree: true, diet: "vegan", timeMin: 30,
    goals: ["weight_loss", "visceral_fat", "muscle_gain", "optimal_health"],
    hue: "bg-[#EAF4E2]",
    ingredients: [
      "150 g firm tofu, pressed & cubed",
      "120 g cooked foxtail millet",
      "1.5 cups mixed veg (beans, carrot, capsicum)",
      "1 tsp sesame oil, ginger, chilli, soy (use tamari if GF-strict)",
      "Sesame seeds to garnish",
    ],
    steps: [
      "Press tofu 10 min; pan-sear cubes till golden, set aside.",
      "Stir-fry veggies on high heat 3–4 min (crisp-tender).",
      "Add tofu, ginger & tamari; toss 1 min.",
      "Serve over warm millet, garnish with sesame.",
    ],
    tip: "Pressing tofu removes water — this is the difference between soggy and golden.",
  },
  {
    id: "egg_toast",
    name: "Veg Egg-White Omelette + Multigrain Toast",
    emoji: "🍳",
    meal: ["breakfast"],
    kcal: 320, protein: 26, carbs: 22, fat: 12, fiber: 5, gi: 50,
    glutenFree: false, diet: "egg", timeMin: 15,
    goals: ["muscle_gain", "weight_loss", "protein_rich"],
    hue: "bg-[#FBF3E2]",
    ingredients: [
      "1 whole egg + 3 whites",
      "Onion, tomato, spinach, chilli (¼ cup)",
      "2 slices multigrain bread",
      "1 tsp oil/ghee, salt, pepper",
    ],
    steps: [
      "Beat eggs with veggies, salt & pepper.",
      "Cook covered on low heat 4–5 min till set; fold.",
      "Toast bread while the omelette sets.",
      "Serve stacked with black coffee or chai (less sugar).",
    ],
    tip: "One whole egg + extra whites gives yolk nutrients with maximum protein.",
  },
  {
    id: "palak_paneer_bajra",
    name: "Palak Paneer + Bajra Roti",
    emoji: "🥬",
    meal: ["lunch", "dinner"],
    kcal: 440, protein: 20, carbs: 38, fat: 22, fiber: 10, gi: 50,
    glutenFree: true, diet: "vegetarian", timeMin: 35,
    goals: ["visceral_fat", "protein_rich", "optimal_health"],
    hue: "bg-[#E4F6EE]",
    ingredients: [
      "100 g paneer cubes",
      "2 cups blanched spinach purée",
      "Onion, tomato, ginger-garlic, 1 tsp ghee",
      "1 bajra roti (40 g flour)",
      "Salt, chilli, garam masala",
    ],
    steps: [
      "Blanch spinach 2 min, shock in cold water, blend smooth.",
      "Sauté onion-tomato in ghee; add spices.",
      "Add purée + paneer; simmer 5 min. Don't overcook — keep it green.",
      "Serve with hot bajra roti and a spoon of curd.",
    ],
    tip: "Blanching + cold shock keeps the palak emerald green instead of olive-brown.",
  },
  {
    id: "chicken_soup",
    name: "Clear Chicken-Veg Soup",
    emoji: "🍲",
    meal: ["snack", "dinner"],
    kcal: 150, protein: 18, carbs: 8, fat: 4, fiber: 2, gi: 15,
    glutenFree: true, diet: "nonveg", timeMin: 25,
    goals: ["weight_loss", "visceral_fat", "protein_rich"],
    hue: "bg-[#FCEFD9]",
    ingredients: [
      "100 g chicken breast, minced/shredded",
      "2 cups clear broth or water",
      "Carrot, beans, cabbage (½ cup)",
      "Ginger, garlic, black pepper, vinegar ½ tsp",
    ],
    steps: [
      "Simmer ginger-garlic in broth 5 min.",
      "Add chicken; poach 8–10 min, skim foam.",
      "Add veggies; cook 4 min.",
      "Season with pepper & vinegar; serve hot.",
    ],
    tip: "A hot protein soup before dinner measurably reduces how much you eat after.",
  },
  {
    id: "sprout_chaat",
    name: "Moong Sprout Chaat",
    emoji: "🌱",
    meal: ["snack", "breakfast"],
    kcal: 180, protein: 11, carbs: 26, fat: 3, fiber: 8, gi: 30,
    glutenFree: true, diet: "vegan", timeMin: 15,
    goals: ["weight_loss", "visceral_fat", "optimal_health"],
    hue: "bg-[#EAF4E2]",
    ingredients: [
      "1 cup moong sprouts (steamed 3 min)",
      "Onion, tomato, cucumber, coriander",
      "Lemon, chaat masala, pinch of salt",
      "1 tbsp peanuts (optional crunch)",
    ],
    steps: [
      "Lightly steam sprouts (keeps them digestible).",
      "Toss with chopped veggies, spices, lemon.",
      "Add peanuts for staying power.",
      "Eat fresh — sprouts dry out fast.",
    ],
    tip: "Raw sprouts can harbor bacteria; a 3-minute steam makes them safe without killing nutrients.",
  },
  {
    id: "overnight_oats",
    name: "Overnight Oats with Whey & Almonds",
    emoji: "🥣",
    meal: ["breakfast"],
    kcal: 380, protein: 30, carbs: 38, fat: 10, fiber: 6, gi: 50,
    glutenFree: true, diet: "vegetarian", timeMin: 5,
    goals: ["muscle_gain", "protein_rich", "weight_loss"],
    hue: "bg-[#FBF3E2]",
    ingredients: [
      "40 g rolled oats (certified GF if needed)",
      "1 scoop (~30 g) vanilla whey or plant protein",
      "150 ml milk or soy milk",
      "1 tbsp chia, 8 almonds, cinnamon",
      "½ banana, sliced",
    ],
    steps: [
      "Mix oats, chia, cinnamon, milk; refrigerate overnight.",
      "In the morning stir in protein powder (add a splash of milk if thick).",
      "Top with banana and almonds.",
      "Grab and go — zero morning cooking.",
    ],
    tip: "Stir whey in the morning, not the night before — it keeps the texture silky.",
  },
  {
    id: "millet_khichdi",
    name: "Veg Millet Khichdi",
    emoji: "🍛",
    meal: ["lunch", "dinner"],
    kcal: 350, protein: 12, carbs: 54, fat: 9, fiber: 9, gi: 52,
    glutenFree: true, diet: "vegan", timeMin: 30,
    goals: ["weight_loss", "optimal_health", "visceral_fat"],
    hue: "bg-[#E4F6EE]",
    ingredients: [
      "50 g foxtail/little millet",
      "30 g moong dal",
      "1 cup mixed veg (peas, carrot, beans)",
      "1 tsp ghee/oil, cumin, hing, turmeric",
      "Salt, ginger",
    ],
    steps: [
      "Rinse millet + dal; soak 15 min.",
      "Temper cumin, hing, ginger in ghee; add veggies & turmeric.",
      "Add millet, dal, salt + 2 cups water; pressure-cook 3 whistles.",
      "Rest, fluff, serve with curd or kadhi.",
    ],
    tip: "The millet-dal combo covers amino acids that each lacks — ancient food science.",
  },
  {
    id: "pb_smoothie",
    name: "Peanut Butter Banana Smoothie",
    emoji: "🥤",
    meal: ["breakfast", "snack"],
    kcal: 350, protein: 18, carbs: 40, fat: 13, fiber: 5, gi: 45,
    glutenFree: true, diet: "vegetarian", timeMin: 5,
    goals: ["weight_gain", "muscle_gain", "protein_rich"],
    hue: "bg-[#FBF3E2]",
    ingredients: [
      "250 ml full-fat milk or soy milk",
      "1 banana",
      "2 tbsp natural peanut butter",
      "1 scoop protein powder (optional → +18 g protein)",
      "2 ice cubes, cinnamon",
    ],
    steps: [
      "Blend everything 45–60 sec till frothy.",
      "Taste; adjust thickness with milk.",
      "Pour, dust with cinnamon.",
      "Post-workout or as a weight-gain snack between meals.",
    ],
    tip: "The easiest 350+ healthy calories for hard-gainers who struggle to eat enough.",
  },
  {
    id: "fish_curry_rice",
    name: "Light Fish Curry + Red Rice",
    emoji: "🐟",
    meal: ["lunch", "dinner"],
    kcal: 460, protein: 32, carbs: 48, fat: 14, fiber: 4, gi: 55,
    glutenFree: true, diet: "nonveg", timeMin: 35,
    goals: ["optimal_health", "protein_rich", "visceral_fat"],
    hue: "bg-[#FCEFD9]",
    ingredients: [
      "150 g firm fish (bangda/rohu), cubed",
      "Onion-tomato-coconut masala (2 tbsp grated coconut)",
      "Turmeric, chilli, coriander powder",
      "1 tsp mustard oil, curry leaves",
      "100 g cooked red/brown rice",
    ],
    steps: [
      "Marinate fish in turmeric + salt 10 min.",
      "Sauté onion, tomato, curry leaves; grind coconut in if using.",
      "Simmer gravy 8 min; slip in fish; cook 6–7 min gently.",
      "Serve with red rice and steamed veggies.",
    ],
    tip: "Never boil fish hard — it breaks. A gentle simmer keeps pieces whole.",
  },
  // ─── Community-requested classics (batch: breakfasts) ─────────────────────
  {
    id: "kanda_poha",
    name: "Kanda Poha with Peanuts",
    emoji: "🍚",
    meal: ["breakfast"],
    kcal: 280, protein: 7, carbs: 44, fat: 8, fiber: 4, gi: 55,
    glutenFree: true, diet: "vegan", timeMin: 15,
    goals: ["optimal_health", "weight_gain", "muscle_gain"],
    hue: "bg-[#FBF3E2]",
    ingredients: [
      "60 g thick poha (flattened rice)",
      "1 onion, 1 potato (optional), curry leaves",
      "1 tbsp peanuts, 1 tsp oil, mustard seeds",
      "Turmeric, green chilli, lemon, coriander",
    ],
    steps: [
      "Rinse poha till just soft; drain and sprinkle salt + turmeric.",
      "Temper mustard, curry leaves, chilli; sauté onion (and potato) till soft.",
      "Fold in poha gently; cover 2 min on low heat.",
      "Finish with peanuts, lemon and coriander.",
    ],
    tip: "Thick poha stays fluffy — thin poha turns mushy. Rinse, don't soak.",
  },
  {
    id: "millet_upma",
    name: "Foxtail Millet Upma",
    emoji: "🥘",
    meal: ["breakfast", "lunch"],
    kcal: 300, protein: 8, carbs: 46, fat: 9, fiber: 7, gi: 50,
    glutenFree: true, diet: "vegan", timeMin: 20,
    goals: ["weight_loss", "visceral_fat", "optimal_health"],
    hue: "bg-[#E4F6EE]",
    ingredients: [
      "60 g foxtail millet (rava texture)",
      "1 cup mixed veg (carrot, beans, peas)",
      "1 tsp oil, mustard, urad dal, curry leaves",
      "Ginger, green chilli, lemon",
    ],
    steps: [
      "Dry-roast millet 3 min till nutty; set aside.",
      "Temper mustard, urad, curry leaves; sauté ginger-chilli and veggies.",
      "Add 1.5 cups water, salt; boil, then rain in the millet, stirring.",
      "Cover on low 8–10 min; fluff with lemon.",
    ],
    tip: "Roasting the millet first keeps grains separate — no lumpy upma.",
  },
  {
    id: "oats_idli",
    name: "Vegetable Oats Idli + Chutney",
    emoji: "🍥",
    meal: ["breakfast"],
    kcal: 260, protein: 11, carbs: 38, fat: 6, fiber: 6, gi: 48,
    glutenFree: true, diet: "vegetarian", timeMin: 25,
    goals: ["weight_loss", "visceral_fat", "optimal_health"],
    hue: "bg-[#E4F6EE]",
    ingredients: [
      "50 g powdered rolled oats (GF-certified if needed)",
      "2 tbsp semolina-free besan or urad flour",
      "1 cup curd + grated carrot, beans, coriander",
      "Eno ½ tsp or ¼ tsp baking soda, salt",
      "Coconut-coriander chutney to serve",
    ],
    steps: [
      "Whisk oats powder, besan, curd + water into idli batter; rest 10 min.",
      "Fold in grated veggies, salt, and the rising agent last.",
      "Steam in idli plates 12–14 min till a skewer comes clean.",
      "Serve warm with chutney or sambar.",
    ],
    tip: "Steam on medium — a hard boil flattens the idlis before they rise.",
  },
  {
    id: "besan_chilla_paneer",
    name: "Besan Chilla with Paneer Stuffing",
    emoji: "🥞",
    meal: ["breakfast"],
    kcal: 290, protein: 14, carbs: 32, fat: 10, fiber: 7, gi: 40,
    glutenFree: true, diet: "vegetarian", timeMin: 15,
    goals: ["weight_loss", "protein_rich", "visceral_fat"],
    hue: "bg-[#F3EAF8]",
    ingredients: [
      "60 g besan (chickpea flour)",
      "40 g grated paneer",
      "Onion, tomato, coriander, green chilli",
      "Ajwain, salt, 1.5 tsp oil",
    ],
    steps: [
      "Whisk besan, ajwain, salt + water into a smooth pouring batter.",
      "Mix paneer with chopped veggies and a pinch of salt for the filling.",
      "Spread a chilla, cook 2 min, spoon filling on half, fold over.",
      "Press and cook 1 min more per side till golden.",
    ],
    tip: "Besan's low GI + paneer's protein keeps you full till lunch — a dieter's chilla.",
  },
  {
    id: "ragi_porridge",
    name: "Salted Ragi Porridge + Chaas",
    emoji: "🌾",
    meal: ["breakfast"],
    kcal: 240, protein: 9, carbs: 36, fat: 6, fiber: 8, gi: 40,
    glutenFree: true, diet: "vegetarian", timeMin: 10,
    goals: ["optimal_health", "weight_loss", "visceral_fat"],
    hue: "bg-[#E4F6EE]",
    ingredients: [
      "40 g ragi (finger millet) flour",
      "250 ml water + pinch of salt",
      "100 ml buttermilk to serve",
      "Cumin, curry leaf tempering (optional)",
    ],
    steps: [
      "Slurry ragi in ½ cup water till lump-free.",
      "Cook on low, stirring, 4–5 min till glossy and thick.",
      "Pour into a bowl; let it set 2 min.",
      "Eat warm with chilled chaas on the side — a classic summer breakfast.",
    ],
    tip: "Ragi is a calcium and iron powerhouse with a low GI — ideal for diabetics.",
  },
  {
    id: "methi_thepla",
    name: "Methi Thepla + Curd",
    emoji: "🫓",
    meal: ["breakfast", "snack"],
    kcal: 310, protein: 10, carbs: 42, fat: 10, fiber: 6, gi: 55,
    glutenFree: false, diet: "vegetarian", timeMin: 25,
    goals: ["optimal_health", "weight_gain"],
    hue: "bg-[#EAF4E2]",
    ingredients: [
      "60 g whole-wheat flour + 2 tbsp besan",
      "½ cup chopped fenugreek (methi) leaves",
      "1 tbsp curd, turmeric, chilli, ajwain",
      "2 tsp oil for cooking",
    ],
    steps: [
      "Knead flour, methi, curd, spices + water into a soft dough; rest 15 min.",
      "Roll thin 6-inch theplas.",
      "Cook on a tawa with a few drops of oil till speckled gold.",
      "Serve with curd or pickle (go easy on the pickle).",
    ],
    tip: "Theplas travel well — a smart tiffin that stays soft for hours.",
  },
  {
    id: "egg_bhurji",
    name: "Masala Egg Bhurji (2 Eggs)",
    emoji: "🍳",
    meal: ["breakfast"],
    kcal: 250, protein: 17, carbs: 8, fat: 16, fiber: 2, gi: 15,
    glutenFree: true, diet: "egg", timeMin: 12,
    goals: ["muscle_gain", "protein_rich", "weight_loss"],
    hue: "bg-[#FBF3E2]",
    ingredients: [
      "2 whole eggs",
      "½ onion, 1 tomato, green chilli",
      "1 tsp oil/ghee, turmeric, pepper, salt",
      "Coriander to finish",
    ],
    steps: [
      "Sauté onion-chilli in oil till golden; add tomato and cook to masala.",
      "Season with turmeric and salt.",
      "Beat eggs, pour in, and scramble on low heat 2–3 min.",
      "Kill the heat while it's still glossy — carryover finishes it.",
    ],
    tip: "Low heat is the whole secret to soft, moist bhurji — high heat makes rubber.",
  },
  {
    id: "paneer_bhurji",
    name: "Low-Oil Paneer Bhurji",
    emoji: "🧀",
    meal: ["breakfast", "dinner"],
    kcal: 300, protein: 20, carbs: 12, fat: 19, fiber: 3, gi: 15,
    glutenFree: true, diet: "vegetarian", timeMin: 15,
    goals: ["muscle_gain", "protein_rich", "visceral_fat"],
    hue: "bg-[#F3EAF8]",
    ingredients: [
      "100 g crumbled paneer",
      "½ onion, 1 tomato, capsicum (¼ cup)",
      "1 tsp oil, cumin, turmeric, chilli, salt",
      "Coriander, lemon",
    ],
    steps: [
      "Temper cumin in oil; brown the onion.",
      "Add tomato-capsicum; cook 3 min to masala.",
      "Fold in paneer crumbs; warm through 2 min — don't fry hard.",
      "Finish with coriander and lemon; eat as-is or roll in a roti.",
    ],
    tip: "Add paneer off the high heat — overcooking turns it chalky.",
  },
  {
    id: "veg_daliya",
    name: "Vegetable Daliya Upma",
    emoji: "🥣",
    meal: ["breakfast", "lunch", "dinner"],
    kcal: 320, protein: 11, carbs: 52, fat: 7, fiber: 9, gi: 55,
    glutenFree: false, diet: "vegetarian", timeMin: 25,
    goals: ["weight_loss", "optimal_health"],
    hue: "bg-[#FBF3E2]",
    ingredients: [
      "55 g broken wheat (daliya)",
      "1 cup mixed vegetables",
      "1 tsp oil, mustard, curry leaves, ginger",
      "Salt, lemon, coriander",
    ],
    steps: [
      "Dry-roast daliya 2–3 min till fragrant.",
      "Temper spices; sauté veggies 3 min.",
      "Add 1.75 cups water + salt; boil and stir in daliya.",
      "Cover on low 10–12 min till soft; fluff with lemon.",
    ],
    tip: "Daliya's coarser crunch digests slowly — a filling, high-fibre comfort bowl.",
  },
  {
    id: "moong_khichdi",
    name: "Classic Moong Dal Khichdi",
    emoji: "🍲",
    meal: ["lunch", "dinner"],
    kcal: 350, protein: 15, carbs: 52, fat: 8, fiber: 7, gi: 55,
    glutenFree: true, diet: "vegetarian", timeMin: 30,
    goals: ["optimal_health", "weight_gain", "muscle_gain"],
    hue: "bg-[#EAF4E2]",
    ingredients: [
      "60 g rice + 40 g moong dal",
      "1 tsp ghee, cumin, hing, turmeric",
      "Ginger, salt, 2.5 cups water",
      "Lemon and papad to serve (baked)",
    ],
    steps: [
      "Rinse rice and dal together; soak 15 min.",
      "Temper cumin and hing in ghee; add turmeric and ginger.",
      "Add rice-dal, salt, water; pressure-cook 3–4 whistles till soft.",
      "Stir, rest 5 min; serve with curd or kadhi.",
    ],
    tip: "The original gut-rest food — soft, balanced and easy on digestion.",
  },
  {
    id: "chole_brown_rice",
    name: "Amritsari-style Chole + Brown Rice",
    emoji: "🍛",
    meal: ["lunch"],
    kcal: 460, protein: 17, carbs: 68, fat: 10, fiber: 14, gi: 52,
    glutenFree: true, diet: "vegan", timeMin: 40,
    goals: ["optimal_health", "muscle_gain", "weight_gain"],
    hue: "bg-[#EAF4E2]",
    ingredients: [
      "70 g dry kabuli chana (or 180 g canned, drained)",
      "Onion-tomato masala, ginger-garlic",
      "Chole masala 1 tsp, anardana or amchur",
      "1 tsp oil, salt; 90 g cooked brown rice",
    ],
    steps: [
      "Pressure-cook soaked chana till tender (or use canned, rinsed).",
      "Build dark onion masala in oil; add ginger-garlic and tomato.",
      "Spice, add chana with cooking liquid; simmer 15 min, lightly mash a few.",
      "Serve over brown rice with onion rings and lemon.",
    ],
    tip: "Mashing a few chana thickens the gravy naturally — no cream needed.",
  },
  {
    id: "palak_dal_jowar",
    name: "Palak Dal Tadka + Jowar Roti",
    emoji: "🥬",
    meal: ["lunch", "dinner"],
    kcal: 380, protein: 17, carbs: 48, fat: 11, fiber: 11, gi: 50,
    glutenFree: true, diet: "vegan", timeMin: 30,
    goals: ["weight_loss", "visceral_fat", "optimal_health"],
    hue: "bg-[#E4F6EE]",
    ingredients: [
      "55 g toor/moong dal",
      "1.5 cups chopped spinach",
      "1 tsp oil, garlic, cumin, red chilli, tomato",
      "1 jowar (sorghum) roti",
    ],
    steps: [
      "Cook dal with turmeric till soft; whisk smooth.",
      "Wilt spinach into the dal 2 min; salt.",
      "Tadka: garlic + cumin + chilli in oil; pour sizzling over the dal.",
      "Serve with warm jowar roti and lemon.",
    ],
    tip: "Iron from palak + vitamin C from lemon/tomato boosts absorption 3×.",
  },
  {
    id: "lauki_chana_dal",
    name: "Lauki-Chana Dal",
    emoji: "🎃",
    meal: ["lunch", "dinner"],
    kcal: 300, protein: 14, carbs: 42, fat: 7, fiber: 9, gi: 45,
    glutenFree: true, diet: "vegan", timeMin: 30,
    goals: ["weight_loss", "visceral_fat", "optimal_health"],
    hue: "bg-[#EAF4E2]",
    ingredients: [
      "50 g chana dal, soaked 1 h",
      "1.5 cups diced lauki (bottle gourd)",
      "1 tsp oil, cumin, hing, green chilli",
      "Turmeric, salt, coriander",
    ],
    steps: [
      "Pressure-cook dal + lauki + turmeric with 1.5 cups water (2–3 whistles).",
      "Temper cumin, hing, chilli in oil; pour into the dal.",
      "Simmer 5 min to marry flavours; salt to taste.",
      "Garnish with coriander; serve with rice or roti.",
    ],
    tip: "Lauki is 92% water and very low GI — volume eating without calories.",
  },
  {
    id: "baingan_bharta",
    name: "Smoky Baingan Bharta + Bajra Roti",
    emoji: "🍆",
    meal: ["lunch", "dinner"],
    kcal: 330, protein: 9, carbs: 36, fat: 16, fiber: 10, gi: 45,
    glutenFree: true, diet: "vegan", timeMin: 35,
    goals: ["weight_loss", "visceral_fat", "optimal_health"],
    hue: "bg-[#FCEFD9]",
    ingredients: [
      "1 large baingan (eggplant, ~250 g)",
      "1 onion, 2 tomatoes, ginger-garlic",
      "1.5 tsp mustard oil, cumin, chilli, garam masala",
      "1 bajra roti",
    ],
    steps: [
      "Roast baingan over flame/oven till collapsed; peel and mash.",
      "Sauté cumin, onion, ginger-garlic in mustard oil till deep gold.",
      "Add tomatoes + spices; cook to masala, then fold in the mash.",
      "Roast bharta 5 min on medium for smokiness; serve with bajra roti.",
    ],
    tip: "Mustard oil must smoke slightly first — raw it bites, smoked it's magic.",
  },
  {
    id: "tandoori_chicken_salad",
    name: "Oven Tandoori Chicken + Salad",
    emoji: "🍗",
    meal: ["lunch", "dinner"],
    kcal: 380, protein: 38, carbs: 10, fat: 20, fiber: 4, gi: 15,
    glutenFree: true, diet: "nonveg", timeMin: 40,
    goals: ["muscle_gain", "visceral_fat", "protein_rich", "weight_loss"],
    hue: "bg-[#FCEFD9]",
    ingredients: [
      "180 g chicken (thigh boneless or breast)",
      "3 tbsp thick curd, 1 tsp tandoori masala",
      "Ginger-garlic, lemon, kashmiri chilli",
      "Cucumber-onion salad with chaat masala",
    ],
    steps: [
      "Score the chicken; rub in ginger-garlic, salt, lemon; rest 15 min.",
      "Marinate in spiced curd 30 min (or overnight for depth).",
      "Bake at 200°C 18–22 min, basting once; char 2 min under the broiler.",
      "Rest 5 min; serve over the crunchy salad.",
    ],
    tip: "Kashmiri chilli gives the classic red without the burn.",
  },
  {
    id: "chicken_curry_brown",
    name: "Home-style Chicken Curry + Brown Rice",
    emoji: "🍛",
    meal: ["lunch", "dinner"],
    kcal: 470, protein: 34, carbs: 46, fat: 15, fiber: 6, gi: 52,
    glutenFree: true, diet: "nonveg", timeMin: 40,
    goals: ["muscle_gain", "protein_rich", "optimal_health", "weight_gain"],
    hue: "bg-[#FCEFD9]",
    ingredients: [
      "150 g chicken, curry cut",
      "1 onion, 2 tomatoes, ginger-garlic paste",
      "1 tsp oil, coriander powder, garam masala, turmeric",
      "90 g cooked brown rice",
    ],
    steps: [
      "Brown onions well in oil — this is the gravy's backbone.",
      "Add ginger-garlic, tomatoes; cook till oil separates.",
      "Add chicken + dry spices; sear 4 min, then simmer covered 18 min.",
      "Rest 5 min; serve with brown rice and salad.",
    ],
    tip: "If oil separates from the masala, your curry is done building — rice in the chicken.",
  },
  {
    id: "pepper_chicken_dry",
    name: "Chettinad-style Pepper Chicken (Dry)",
    emoji: "🌶️",
    meal: ["lunch", "dinner", "snack"],
    kcal: 280, protein: 30, carbs: 12, fat: 13, fiber: 3, gi: 20,
    glutenFree: true, diet: "nonveg", timeMin: 25,
    goals: ["protein_rich", "muscle_gain", "weight_loss", "visceral_fat"],
    hue: "bg-[#FCEFD9]",
    ingredients: [
      "150 g chicken breast, bite-size",
      "1 tsp crushed black pepper, fennel ¼ tsp",
      "Curry leaves, onion, ginger-garlic",
      "1.5 tsp coconut oil, turmeric, salt",
    ],
    steps: [
      "Sear chicken with turmeric + salt; set aside when 80% done.",
      "In the same pan, fry onions, ginger-garlic, curry leaves.",
      "Return chicken; dry-roast with pepper + fennel 4–5 min.",
      "Finish with a final crack of pepper and lemon.",
    ],
    tip: "Crush pepper just before cooking — pre-ground pepper loses its aroma fast.",
  },
  {
    id: "prawn_masala",
    name: "Prawn Masala (10-min)",
    emoji: "🦐",
    meal: ["lunch", "dinner"],
    kcal: 320, protein: 28, carbs: 18, fat: 14, fiber: 4, gi: 35,
    glutenFree: true, diet: "nonveg", timeMin: 20,
    goals: ["protein_rich", "muscle_gain", "visceral_fat"],
    hue: "bg-[#FCEFD9]",
    ingredients: [
      "180 g prawns, cleaned",
      "1 onion, 2 tomatoes, ginger-garlic",
      "1.5 tsp oil, chilli, turmeric, garam masala",
      "Curry leaves, coriander, lemon",
    ],
    steps: [
      "Marinate prawns in turmeric, chilli, salt 10 min.",
      "Build quick onion-tomato masala in oil, 6–7 min.",
      "Add prawns; cook exactly 3–4 min till they curl and turn opaque.",
      "Finish with coriander + lemon; serve immediately.",
    ],
    tip: "Prawns go from perfect to rubber in a minute — pull them as soon as they curl.",
  },
  {
    id: "egg_curry_light",
    name: "Light Egg Curry (No Coconut)",
    emoji: "🥚",
    meal: ["lunch", "dinner"],
    kcal: 330, protein: 18, carbs: 20, fat: 18, fiber: 4, gi: 35,
    glutenFree: true, diet: "egg", timeMin: 25,
    goals: ["muscle_gain", "protein_rich", "optimal_health"],
    hue: "bg-[#FBF3E2]",
    ingredients: [
      "3 boiled eggs",
      "1 onion, 2 tomatoes, ginger-garlic",
      "1.5 tsp oil, turmeric, chilli, coriander powder",
      "2 tbsp curd whisked (for creaminess)",
    ],
    steps: [
      "Halve boiled eggs; dust with turmeric, sear lightly in oil.",
      "Build onion-tomato masala; blend smooth if you like a silky gravy.",
      "Simmer masala + ½ cup water 6 min; whisk in curd off the heat.",
      "Slide eggs in; warm 2 min. Never boil after adding curd.",
    ],
    tip: "Lightly searing eggs gives them a golden jacket that holds the gravy.",
  },
  {
    id: "soya_keema_roti",
    name: "Soya Keema + Phulka",
    emoji: "🌱",
    meal: ["lunch", "dinner"],
    kcal: 400, protein: 28, carbs: 42, fat: 12, fiber: 10, gi: 50,
    glutenFree: false, diet: "vegetarian", timeMin: 30,
    goals: ["muscle_gain", "protein_rich", "weight_loss"],
    hue: "bg-[#EAF4E2]",
    ingredients: [
      "50 g soya granules (rehydrated, squeezed)",
      "1 onion, 2 tomatoes, ginger-garlic",
      "1.5 tsp oil, garam masala, coriander powder",
      "2 phulkas (40 g atta total), peas ¼ cup",
    ],
    steps: [
      "Soak soya in hot water 10 min; drain and squeeze very dry.",
      "Brown onions in oil; add ginger-garlic, tomatoes, spices.",
      "Add soya + peas; cook 6–7 min till keema-textured.",
      "Serve with hot phulkas, onion slices and lemon.",
    ],
    tip: "Squeeze the granules bone-dry or the keema turns soggy.",
  },
  {
    id: "kala_chana_sundal",
    name: "Kala Chana Sundal",
    emoji: "🌰",
    meal: ["snack"],
    kcal: 170, protein: 9, carbs: 22, fat: 5, fiber: 8, gi: 30,
    glutenFree: true, diet: "vegan", timeMin: 20,
    goals: ["weight_loss", "visceral_fat", "protein_rich"],
    hue: "bg-[#EAF4E2]",
    ingredients: [
      "60 g cooked kala chana",
      "1 tsp coconut oil, mustard, curry leaves",
      "2 tbsp grated coconut",
      "Asafoetida, green chilli, lemon",
    ],
    steps: [
      "Pressure-cook soaked chana till just tender (not mushy).",
      "Temper mustard, chilli, curry leaves, hing in coconut oil.",
      "Toss in the chana + salt; warm 2 min.",
      "Finish with coconut and lemon; eat warm or at room temperature.",
    ],
    tip: "South India's protein-forward evening snack — better than any biscuit.",
  },
  {
    id: "masala_chaas",
    name: "Masala Chaas (Spiced Buttermilk)",
    emoji: "🥛",
    meal: ["snack"],
    kcal: 60, protein: 4, carbs: 6, fat: 2, fiber: 0, gi: 15,
    glutenFree: true, diet: "vegetarian", timeMin: 5,
    goals: ["weight_loss", "visceral_fat", "optimal_health"],
    hue: "bg-[#F3EAF8]",
    ingredients: [
      "200 ml curd + 150 ml chilled water",
      "Roasted cumin powder, black salt",
      "Coriander, curry leaf, green chilli (optional)",
      "Pinch of ginger (fresh grated)",
    ],
    steps: [
      "Whisk curd smooth with water — no lumps.",
      "Season with roasted cumin + black salt.",
      "Crush coriander, curry leaf, chilli lightly; stir in.",
      "Serve cold — the classic Indian cooling drink.",
    ],
    tip: "The 3 pm chaas replaces the 3 pm biscuit — same ritual, 60 calories.",
  },
  {
    id: "makhana_roast",
    name: "Roasted Masala Makhana",
    emoji: "🍿",
    meal: ["snack"],
    kcal: 160, protein: 5, carbs: 22, fat: 6, fiber: 3, gi: 35,
    glutenFree: true, diet: "vegetarian", timeMin: 12,
    goals: ["weight_loss", "optimal_health"],
    hue: "bg-[#FBF3E2]",
    ingredients: [
      "25 g (about 1 cup) phool makhana",
      "1 tsp ghee",
      "Roasted cumin, chaat masala, black salt",
      "Pinch of chilli powder",
    ],
    steps: [
      "Roast makhana in dry ghee on low heat 6–8 min till crisp.",
      "Cool 2 min — they crisp up more as they cool.",
      "Toss with ghee and spices.",
      "Store airtight for a 3-day snack stash.",
    ],
    tip: "Test one: if it snaps clean, the batch is done. Chewy means 2 more minutes.",
  },
  {
    id: "fruit_chaat",
    name: "Spiced Fruit Chaat",
    emoji: "🍎",
    meal: ["snack", "breakfast"],
    kcal: 140, protein: 2, carbs: 30, fat: 1, fiber: 6, gi: 40,
    glutenFree: true, diet: "vegan", timeMin: 8,
    goals: ["weight_loss", "optimal_health", "visceral_fat"],
    hue: "bg-[#EAF4E2]",
    ingredients: [
      "1 guava or apple, ½ papaya cup",
      "Pomegranate pearls ¼ cup",
      "Chaat masala, black salt, roasted cumin",
      "Lemon, mint leaves",
    ],
    steps: [
      "Chop fruit into bite-size pieces.",
      "Toss with spices and lemon just before eating.",
      "Tear mint over the top.",
      "Chill fruit beforehand for the best contrast.",
    ],
    tip: "Whole fruit's fibre slows the sugar — juice never gets that halo.",
  },
  {
    id: "egg_chaat",
    name: "Boiled Egg Chaat",
    emoji: "🥚",
    meal: ["snack"],
    kcal: 180, protein: 12, carbs: 10, fat: 9, fiber: 2, gi: 20,
    glutenFree: true, diet: "egg", timeMin: 10,
    goals: ["weight_loss", "protein_rich", "muscle_gain"],
    hue: "bg-[#FBF3E2]",
    ingredients: [
      "2 boiled eggs, quarters",
      "½ onion, ½ tomato, coriander",
      "Chaat masala, black salt, roasted cumin",
      "Lemon, tamarind chutney 1 tsp (optional)",
    ],
    steps: [
      "Boil eggs 9 min; cool, peel, quarter.",
      "Toss gently with onion, tomato, spices.",
      "Dress with lemon (and tamarind if you like sweet-sour).",
      "Eat immediately — the onions should stay crisp.",
    ],
    tip: "Evening protein is the most skipped meal — this fixes it in 10 minutes.",
  },
  {
    id: "curd_rice_brown",
    name: "Brown Rice Curd Rice",
    emoji: "🍚",
    meal: ["lunch"],
    kcal: 340, protein: 11, carbs: 52, fat: 8, fiber: 5, gi: 50,
    glutenFree: true, diet: "vegetarian", timeMin: 15,
    goals: ["optimal_health", "muscle_gain", "weight_gain"],
    hue: "bg-[#F3EAF8]",
    ingredients: [
      "90 g cooked brown rice (cooled)",
      "200 ml curd, 2 tbsp milk",
      "1 tsp oil, mustard, urad dal, ginger, curry leaves",
      "Pomegranate + coriander to top",
    ],
    steps: [
      "Mash warm-ish rice lightly; mix in curd + milk; salt.",
      "Temper mustard, urad, ginger, curry leaves in oil.",
      "Pour the tadka over; fold once.",
      "Top with pomegranate; serve cool.",
    ],
    tip: "Brown rice drops the GI by ~15 points versus white — same comfort, steadier sugar.",
  },
];
