// ─── NourishIQ Recipe Collection ────────────────────────────────────────────
// Goal-aligned recipes with estimated macros per serving.
// ─────────────────────────────────────────────────────────────────────────────

import type { Recipe } from "./types";

export const RECIPES: Recipe[] = [
  {
    id: "chicken_quinoa_bowl",
    region: "Global",
    name: "Grilled Chicken & Quinoa Bowl",
    emoji: "🍗",
    meal: ["lunch", "dinner"],
    kcal: 480, protein: 42, carbs: 45, fat: 12, fiber: 8, gi: 50,
    glutenFree: true, diet: "nonveg", timeMin: 30,
    goals: ["muscle_gain", "weight_loss", "visceral_fat", "protein_rich"],
    hue: "bg-[#E4F6EE]",
    ingredients: [
      "150 g chicken breast, skinless",
      "120 g cooked quinoa (½ katori uncooked)",
      "1 cup broccoli + capsicum, chopped",
      "2 tsp olive oil, ½ lemon, black pepper",
      "Pink salt, garlic, mixed herbs",
    ],
    steps: [
      "Marinate chicken in lemon, garlic, herbs & 1 tsp oil for 15 min.",
      "Grill 6–7 min per side until juices run clear; rest 5 min, slice.",
      "Sauté broccoli & capsicum in remaining oil, 3–4 min (keep crunchy).",
      "Assemble: quinoa base → veggies → chicken. Season and serve warm.",
    ],
    tip: "Resting the chicken after cooking keeps it juicy — cutting early loses moisture.",
  },
  {
    id: "paneer_tikka",
    region: "North India",
    name: "Oven Paneer Tikka + Mint Chutney",
    emoji: "🧈",
    meal: ["snack", "dinner"],
    kcal: 320, protein: 22, carbs: 12, fat: 20, fiber: 4, gi: 15,
    glutenFree: true, diet: "vegetarian", timeMin: 25,
    goals: ["muscle_gain", "protein_rich", "visceral_fat", "optimal_health"],
    hue: "bg-[#F3EAF8]",
    ingredients: [
      "150 g paneer, 2 cm cubes",
      "3 tbsp thick curd (hung)",
      "1 tsp tandoori masala, ¼ tsp turmeric, red chilli",
      "Onion & capsicum petals, lemon",
      "Mint-coriander chutney to serve",
    ],
    steps: [
      "Whisk curd + spices into a thick marinade.",
      "Coat paneer and veggies; rest 20 min (or 2 h for deeper flavour).",
      "Skewer and bake at 200°C for 15–18 min, turning once.",
      "Char 2 min on tawa/stove flame for smokiness. Serve with chutney.",
    ],
    tip: "Hung curd clings better than watery curd — drain 15 minutes in a muslin cloth.",
  },
  {
    id: "moong_chilla",
    region: "North India",
    name: "Moong Dal Chilla (2) with Chutney",
    emoji: "🥞",
    meal: ["breakfast"],
    kcal: 280, protein: 16, carbs: 34, fat: 8, fiber: 7, gi: 45,
    glutenFree: true, diet: "vegetarian", timeMin: 20,
    goals: ["weight_loss", "visceral_fat", "protein_rich", "optimal_health"],
    hue: "bg-[#EAF4E2]",
    ingredients: [
      "60 g yellow moong dal, soaked 3–4 h",
      "1 green chilli, ginger, coriander",
      "¼ tsp hing, salt, 1 tsp oil",
      "Grated carrot/onion for stuffing (optional)",
    ],
    steps: [
      "Drain dal; blend with chilli, ginger & ¼ cup water into a smooth batter.",
      "Stir in salt, hing, coriander, chopped veggies.",
      "Spread 2 chillas on a hot non-stick tawa with a few drops of oil.",
      "Cook 2–3 min per side till golden. Serve with green chutney.",
    ],
    tip: "Thin batter = crisp chilla; thick = soft. Adjust with water one spoon at a time.",
  },
  {
    id: "ragi_dosa",
    region: "Karnataka",
    name: "Ragi Dosa + Sambar",
    emoji: "🌾",
    meal: ["breakfast", "dinner"],
    kcal: 340, protein: 11, carbs: 52, fat: 8, fiber: 9, gi: 52,
    glutenFree: true, diet: "vegetarian", timeMin: 25,
    goals: ["weight_loss", "visceral_fat", "optimal_health"],
    hue: "bg-[#E4F6EE]",
    ingredients: [
      "40 g ragi flour, 20 g rice flour",
      "2 tbsp curd, cumin, green chilli, curry leaves",
      "Salt, 1 tsp oil",
      "1 katori sambar (toor dal + veggies)",
    ],
    steps: [
      "Whisk flours, curd, salt + 1.5 cups water into a thin batter; rest 15 min.",
      "Season with cumin, chilli and curry leaves.",
      "Pour thin dosas on a hot tawa, drizzle oil, cook 2–3 min per side.",
      "Serve hot with sambar and a spoon of coconut chutney.",
    ],
    tip: "No fermentation needed — this instant-batter version keeps mornings fast.",
  },
  {
    id: "yogurt_berry_bowl",
    region: "Global",
    name: "Greek Yogurt Berry Bowl with Chia",
    emoji: "🫐",
    meal: ["breakfast", "snack"],
    kcal: 300, protein: 24, carbs: 30, fat: 9, fiber: 7, gi: 35,
    glutenFree: true, diet: "vegetarian", timeMin: 5,
    goals: ["muscle_gain", "weight_loss", "protein_rich", "optimal_health"],
    hue: "bg-[#F3EAF8]",
    ingredients: [
      "200 g plain Greek yogurt",
      "¾ cup mixed berries or 1 chopped guava",
      "1 tbsp chia seeds",
      "8 chopped almonds",
      "1 tsp honey (optional)",
    ],
    steps: [
      "Spoon yogurt into a bowl.",
      "Top with fruit, chia and almonds.",
      "Drizzle honey only if needed — berries bring natural sweetness.",
      "Let chia hydrate 5 min before eating.",
    ],
    tip: "24 g of protein before 10 am is the easiest way to hit a high-protein day.",
  },
  {
    id: "rajma_rice",
    region: "North India",
    name: "Rajma with Brown Rice & Salad",
    emoji: "🍛",
    meal: ["lunch"],
    kcal: 450, protein: 16, carbs: 72, fat: 8, fiber: 13, gi: 55,
    glutenFree: true, diet: "vegan", timeMin: 45,
    goals: ["optimal_health", "weight_gain", "weight_loss"],
    hue: "bg-[#EAF4E2]",
    ingredients: [
      "60 g dry rajma (soaked overnight)",
      "80 g cooked brown rice",
      "Onion-tomato masala, ginger-garlic",
      "1 tsp mustard oil, garam masala",
      "Cucumber-onion salad with lemon",
    ],
    steps: [
      "Pressure-cook soaked rajma with salt till soft (4–5 whistles).",
      "Build masala: onion → tomato → spices; add rajma with cooking water.",
      "Simmer 15 min till gravy thickens.",
      "Plate rice + rajma + salad; finish with lemon and raw onion.",
    ],
    tip: "The classic carb+legume pairing = complete amino-acid profile at low cost.",
  },
  {
    id: "salmon_greens",
    region: "Global",
    name: "Pan-Seared Salmon & Sautéed Greens",
    emoji: "🐟",
    meal: ["dinner"],
    kcal: 430, protein: 36, carbs: 10, fat: 26, fiber: 4, gi: 15,
    glutenFree: true, diet: "nonveg", timeMin: 20,
    goals: ["visceral_fat", "optimal_health", "protein_rich"],
    hue: "bg-[#FCEFD9]",
    ingredients: [
      "130 g salmon fillet",
      "2 cups spinach + green beans",
      "2 tsp olive oil, 2 garlic cloves",
      "Lemon, black pepper, salt",
    ],
    steps: [
      "Pat salmon dry; season. Sear skin-side down 4 min in hot oil.",
      "Flip, cook 3 min more; rest on a plate.",
      "Sauté garlic, then greens 2 min till just wilted.",
      "Plate with lemon squeeze and pepper.",
    ],
    tip: "Crispy skin = dry skin. Don't move the fillet for the first 4 minutes.",
  },
  {
    id: "tofu_stirfry",
    region: "Global",
    name: "Tofu-Veg Stir-fry with Foxtail Millet",
    emoji: "🌱",
    meal: ["lunch", "dinner"],
    kcal: 420, protein: 24, carbs: 46, fat: 14, fiber: 8, gi: 50,
    glutenFree: true, diet: "vegan", timeMin: 30,
    goals: ["weight_loss", "visceral_fat", "muscle_gain", "optimal_health"],
    hue: "bg-[#EAF4E2]",
    ingredients: [
      "150 g firm tofu, pressed & cubed",
      "120 g cooked foxtail millet",
      "1.5 cups mixed veg (beans, carrot, capsicum)",
      "1 tsp sesame oil, ginger, chilli, soy (use tamari if GF-strict)",
      "Sesame seeds to garnish",
    ],
    steps: [
      "Press tofu 10 min; pan-sear cubes till golden, set aside.",
      "Stir-fry veggies on high heat 3–4 min (crisp-tender).",
      "Add tofu, ginger & tamari; toss 1 min.",
      "Serve over warm millet, garnish with sesame.",
    ],
    tip: "Pressing tofu removes water — this is the difference between soggy and golden.",
  },
  {
    id: "egg_toast",
    region: "Global",
    name: "Veg Egg-White Omelette + Multigrain Toast",
    emoji: "🍳",
    meal: ["breakfast"],
    kcal: 320, protein: 26, carbs: 22, fat: 12, fiber: 5, gi: 50,
    glutenFree: false, diet: "egg", timeMin: 15,
    goals: ["muscle_gain", "weight_loss", "protein_rich"],
    hue: "bg-[#FBF3E2]",
    ingredients: [
      "1 whole egg + 3 whites",
      "Onion, tomato, spinach, chilli (¼ cup)",
      "2 slices multigrain bread",
      "1 tsp oil/ghee, salt, pepper",
    ],
    steps: [
      "Beat eggs with veggies, salt & pepper.",
      "Cook covered on low heat 4–5 min till set; fold.",
      "Toast bread while the omelette sets.",
      "Serve stacked with black coffee or chai (less sugar).",
    ],
    tip: "One whole egg + extra whites gives yolk nutrients with maximum protein.",
  },
  {
    id: "palak_paneer_bajra",
    region: "North India",
    name: "Palak Paneer + Bajra Roti",
    emoji: "🥬",
    meal: ["lunch", "dinner"],
    kcal: 440, protein: 20, carbs: 38, fat: 22, fiber: 10, gi: 50,
    glutenFree: true, diet: "vegetarian", timeMin: 35,
    goals: ["visceral_fat", "protein_rich", "optimal_health"],
    hue: "bg-[#E4F6EE]",
    ingredients: [
      "100 g paneer cubes",
      "2 cups blanched spinach purée",
      "Onion, tomato, ginger-garlic, 1 tsp ghee",
      "1 bajra roti (40 g flour)",
      "Salt, chilli, garam masala",
    ],
    steps: [
      "Blanch spinach 2 min, shock in cold water, blend smooth.",
      "Sauté onion-tomato in ghee; add spices.",
      "Add purée + paneer; simmer 5 min. Don't overcook — keep it green.",
      "Serve with hot bajra roti and a spoon of curd.",
    ],
    tip: "Blanching + cold shock keeps the palak emerald green instead of olive-brown.",
  },
  {
    id: "chicken_soup",
    region: "Global",
    name: "Clear Chicken-Veg Soup",
    emoji: "🍲",
    meal: ["snack", "dinner"],
    kcal: 150, protein: 18, carbs: 8, fat: 4, fiber: 2, gi: 15,
    glutenFree: true, diet: "nonveg", timeMin: 25,
    goals: ["weight_loss", "visceral_fat", "protein_rich"],
    hue: "bg-[#FCEFD9]",
    ingredients: [
      "100 g chicken breast, minced/shredded",
      "2 cups clear broth or water",
      "Carrot, beans, cabbage (½ cup)",
      "Ginger, garlic, black pepper, vinegar ½ tsp",
    ],
    steps: [
      "Simmer ginger-garlic in broth 5 min.",
      "Add chicken; poach 8–10 min, skim foam.",
      "Add veggies; cook 4 min.",
      "Season with pepper & vinegar; serve hot.",
    ],
    tip: "A hot protein soup before dinner measurably reduces how much you eat after.",
  },
  {
    id: "sprout_chaat",
    region: "Pan-India",
    name: "Moong Sprout Chaat",
    emoji: "🌱",
    meal: ["snack", "breakfast"],
    kcal: 180, protein: 11, carbs: 26, fat: 3, fiber: 8, gi: 30,
    glutenFree: true, diet: "vegan", timeMin: 15,
    goals: ["weight_loss", "visceral_fat", "optimal_health"],
    hue: "bg-[#EAF4E2]",
    ingredients: [
      "1 cup moong sprouts (steamed 3 min)",
      "Onion, tomato, cucumber, coriander",
      "Lemon, chaat masala, pinch of salt",
      "1 tbsp peanuts (optional crunch)",
    ],
    steps: [
      "Lightly steam sprouts (keeps them digestible).",
      "Toss with chopped veggies, spices, lemon.",
      "Add peanuts for staying power.",
      "Eat fresh — sprouts dry out fast.",
    ],
    tip: "Raw sprouts can harbor bacteria; a 3-minute steam makes them safe without killing nutrients.",
  },
  {
    id: "overnight_oats",
    region: "Global",
    name: "Overnight Oats with Whey & Almonds",
    emoji: "🥣",
    meal: ["breakfast"],
    kcal: 380, protein: 30, carbs: 38, fat: 10, fiber: 6, gi: 50,
    glutenFree: true, diet: "vegetarian", timeMin: 5,
    goals: ["muscle_gain", "protein_rich", "weight_loss"],
    hue: "bg-[#FBF3E2]",
    ingredients: [
      "40 g rolled oats (certified GF if needed)",
      "1 scoop (~30 g) vanilla whey or plant protein",
      "150 ml milk or soy milk",
      "1 tbsp chia, 8 almonds, cinnamon",
      "½ banana, sliced",
    ],
    steps: [
      "Mix oats, chia, cinnamon, milk; refrigerate overnight.",
      "In the morning stir in protein powder (add a splash of milk if thick).",
      "Top with banana and almonds.",
      "Grab and go — zero morning cooking.",
    ],
    tip: "Stir whey in the morning, not the night before — it keeps the texture silky.",
  },
  {
    id: "millet_khichdi",
    region: "Pan-India",
    name: "Veg Millet Khichdi",
    emoji: "🍛",
    meal: ["lunch", "dinner"],
    kcal: 350, protein: 12, carbs: 54, fat: 9, fiber: 9, gi: 52,
    glutenFree: true, diet: "vegan", timeMin: 30,
    goals: ["weight_loss", "optimal_health", "visceral_fat"],
    hue: "bg-[#E4F6EE]",
    ingredients: [
      "50 g foxtail/little millet",
      "30 g moong dal",
      "1 cup mixed veg (peas, carrot, beans)",
      "1 tsp ghee/oil, cumin, hing, turmeric",
      "Salt, ginger",
    ],
    steps: [
      "Rinse millet + dal; soak 15 min.",
      "Temper cumin, hing, ginger in ghee; add veggies & turmeric.",
      "Add millet, dal, salt + 2 cups water; pressure-cook 3 whistles.",
      "Rest, fluff, serve with curd or kadhi.",
    ],
    tip: "The millet-dal combo covers amino acids that each lacks — ancient food science.",
  },
  {
    id: "pb_smoothie",
    region: "Global",
    name: "Peanut Butter Banana Smoothie",
    emoji: "🥤",
    meal: ["breakfast", "snack"],
    kcal: 350, protein: 18, carbs: 40, fat: 13, fiber: 5, gi: 45,
    glutenFree: true, diet: "vegetarian", timeMin: 5,
    goals: ["weight_gain", "muscle_gain", "protein_rich"],
    hue: "bg-[#FBF3E2]",
    ingredients: [
      "250 ml full-fat milk or soy milk",
      "1 banana",
      "2 tbsp natural peanut butter",
      "1 scoop protein powder (optional → +18 g protein)",
      "2 ice cubes, cinnamon",
    ],
    steps: [
      "Blend everything 45–60 sec till frothy.",
      "Taste; adjust thickness with milk.",
      "Pour, dust with cinnamon.",
      "Post-workout or as a weight-gain snack between meals.",
    ],
    tip: "The easiest 350+ healthy calories for hard-gainers who struggle to eat enough.",
  },
  {
    id: "fish_curry_rice",
    region: "South India",
    name: "Light Fish Curry + Red Rice",
    emoji: "🐟",
    meal: ["lunch", "dinner"],
    kcal: 460, protein: 32, carbs: 48, fat: 14, fiber: 4, gi: 55,
    glutenFree: true, diet: "nonveg", timeMin: 35,
    goals: ["optimal_health", "protein_rich", "visceral_fat"],
    hue: "bg-[#FCEFD9]",
    ingredients: [
      "150 g firm fish (bangda/rohu), cubed",
      "Onion-tomato-coconut masala (2 tbsp grated coconut)",
      "Turmeric, chilli, coriander powder",
      "1 tsp mustard oil, curry leaves",
      "100 g cooked red/brown rice",
    ],
    steps: [
      "Marinate fish in turmeric + salt 10 min.",
      "Sauté onion, tomato, curry leaves; grind coconut in if using.",
      "Simmer gravy 8 min; slip in fish; cook 6–7 min gently.",
      "Serve with red rice and steamed veggies.",
    ],
    tip: "Never boil fish hard — it breaks. A gentle simmer keeps pieces whole.",
  },
  // ─── Community-requested classics (batch: breakfasts) ─────────────────────
  {
    id: "kanda_poha",
    region: "Maharashtra",
    name: "Kanda Poha with Peanuts",
    emoji: "🍚",
    meal: ["breakfast"],
    kcal: 280, protein: 7, carbs: 44, fat: 8, fiber: 4, gi: 55,
    glutenFree: true, diet: "vegan", timeMin: 15,
    goals: ["optimal_health", "weight_gain", "muscle_gain"],
    hue: "bg-[#FBF3E2]",
    ingredients: [
      "60 g thick poha (flattened rice)",
      "1 onion, 1 potato (optional), curry leaves",
      "1 tbsp peanuts, 1 tsp oil, mustard seeds",
      "Turmeric, green chilli, lemon, coriander",
    ],
    steps: [
      "Rinse poha till just soft; drain and sprinkle salt + turmeric.",
      "Temper mustard, curry leaves, chilli; sauté onion (and potato) till soft.",
      "Fold in poha gently; cover 2 min on low heat.",
      "Finish with peanuts, lemon and coriander.",
    ],
    tip: "Thick poha stays fluffy — thin poha turns mushy. Rinse, don't soak.",
  },
  {
    id: "millet_upma",
    region: "South India",
    name: "Foxtail Millet Upma",
    emoji: "🥘",
    meal: ["breakfast", "lunch"],
    kcal: 300, protein: 8, carbs: 46, fat: 9, fiber: 7, gi: 50,
    glutenFree: true, diet: "vegan", timeMin: 20,
    goals: ["weight_loss", "visceral_fat", "optimal_health"],
    hue: "bg-[#E4F6EE]",
    ingredients: [
      "60 g foxtail millet (rava texture)",
      "1 cup mixed veg (carrot, beans, peas)",
      "1 tsp oil, mustard, urad dal, curry leaves",
      "Ginger, green chilli, lemon",
    ],
    steps: [
      "Dry-roast millet 3 min till nutty; set aside.",
      "Temper mustard, urad, curry leaves; sauté ginger-chilli and veggies.",
      "Add 1.5 cups water, salt; boil, then rain in the millet, stirring.",
      "Cover on low 8–10 min; fluff with lemon.",
    ],
    tip: "Roasting the millet first keeps grains separate — no lumpy upma.",
  },
  {
    id: "oats_idli",
    region: "South India",
    name: "Vegetable Oats Idli + Chutney",
    emoji: "🍥",
    meal: ["breakfast"],
    kcal: 260, protein: 11, carbs: 38, fat: 6, fiber: 6, gi: 48,
    glutenFree: true, diet: "vegetarian", timeMin: 25,
    goals: ["weight_loss", "visceral_fat", "optimal_health"],
    hue: "bg-[#E4F6EE]",
    ingredients: [
      "50 g powdered rolled oats (GF-certified if needed)",
      "2 tbsp semolina-free besan or urad flour",
      "1 cup curd + grated carrot, beans, coriander",
      "Eno ½ tsp or ¼ tsp baking soda, salt",
      "Coconut-coriander chutney to serve",
    ],
    steps: [
      "Whisk oats powder, besan, curd + water into idli batter; rest 10 min.",
      "Fold in grated veggies, salt, and the rising agent last.",
      "Steam in idli plates 12–14 min till a skewer comes clean.",
      "Serve warm with chutney or sambar.",
    ],
    tip: "Steam on medium — a hard boil flattens the idlis before they rise.",
  },
  {
    id: "besan_chilla_paneer",
    region: "North India",
    name: "Besan Chilla with Paneer Stuffing",
    emoji: "🥞",
    meal: ["breakfast"],
    kcal: 290, protein: 14, carbs: 32, fat: 10, fiber: 7, gi: 40,
    glutenFree: true, diet: "vegetarian", timeMin: 15,
    goals: ["weight_loss", "protein_rich", "visceral_fat"],
    hue: "bg-[#F3EAF8]",
    ingredients: [
      "60 g besan (chickpea flour)",
      "40 g grated paneer",
      "Onion, tomato, coriander, green chilli",
      "Ajwain, salt, 1.5 tsp oil",
    ],
    steps: [
      "Whisk besan, ajwain, salt + water into a smooth pouring batter.",
      "Mix paneer with chopped veggies and a pinch of salt for the filling.",
      "Spread a chilla, cook 2 min, spoon filling on half, fold over.",
      "Press and cook 1 min more per side till golden.",
    ],
    tip: "Besan's low GI + paneer's protein keeps you full till lunch — a dieter's chilla.",
  },
  {
    id: "ragi_porridge",
    region: "Karnataka",
    name: "Salted Ragi Porridge + Chaas",
    emoji: "🌾",
    meal: ["breakfast"],
    kcal: 240, protein: 9, carbs: 36, fat: 6, fiber: 8, gi: 40,
    glutenFree: true, diet: "vegetarian", timeMin: 10,
    goals: ["optimal_health", "weight_loss", "visceral_fat"],
    hue: "bg-[#E4F6EE]",
    ingredients: [
      "40 g ragi (finger millet) flour",
      "250 ml water + pinch of salt",
      "100 ml buttermilk to serve",
      "Cumin, curry leaf tempering (optional)",
    ],
    steps: [
      "Slurry ragi in ½ cup water till lump-free.",
      "Cook on low, stirring, 4–5 min till glossy and thick.",
      "Pour into a bowl; let it set 2 min.",
      "Eat warm with chilled chaas on the side — a classic summer breakfast.",
    ],
    tip: "Ragi is a calcium and iron powerhouse with a low GI — ideal for diabetics.",
  },
  {
    id: "methi_thepla",
    region: "Gujarat",
    name: "Methi Thepla + Curd",
    emoji: "🫓",
    meal: ["breakfast", "snack"],
    kcal: 310, protein: 10, carbs: 42, fat: 10, fiber: 6, gi: 55,
    glutenFree: false, diet: "vegetarian", timeMin: 25,
    goals: ["optimal_health", "weight_gain"],
    hue: "bg-[#EAF4E2]",
    ingredients: [
      "60 g whole-wheat flour + 2 tbsp besan",
      "½ cup chopped fenugreek (methi) leaves",
      "1 tbsp curd, turmeric, chilli, ajwain",
      "2 tsp oil for cooking",
    ],
    steps: [
      "Knead flour, methi, curd, spices + water into a soft dough; rest 15 min.",
      "Roll thin 6-inch theplas.",
      "Cook on a tawa with a few drops of oil till speckled gold.",
      "Serve with curd or pickle (go easy on the pickle).",
    ],
    tip: "Theplas travel well — a smart tiffin that stays soft for hours.",
  },
  {
    id: "egg_bhurji",
    region: "North India",
    name: "Masala Egg Bhurji (2 Eggs)",
    emoji: "🍳",
    meal: ["breakfast"],
    kcal: 250, protein: 17, carbs: 8, fat: 16, fiber: 2, gi: 15,
    glutenFree: true, diet: "egg", timeMin: 12,
    goals: ["muscle_gain", "protein_rich", "weight_loss"],
    hue: "bg-[#FBF3E2]",
    ingredients: [
      "2 whole eggs",
      "½ onion, 1 tomato, green chilli",
      "1 tsp oil/ghee, turmeric, pepper, salt",
      "Coriander to finish",
    ],
    steps: [
      "Sauté onion-chilli in oil till golden; add tomato and cook to masala.",
      "Season with turmeric and salt.",
      "Beat eggs, pour in, and scramble on low heat 2–3 min.",
      "Kill the heat while it's still glossy — carryover finishes it.",
    ],
    tip: "Low heat is the whole secret to soft, moist bhurji — high heat makes rubber.",
  },
  {
    id: "paneer_bhurji",
    region: "North India",
    name: "Low-Oil Paneer Bhurji",
    emoji: "🧀",
    meal: ["breakfast", "dinner"],
    kcal: 300, protein: 20, carbs: 12, fat: 19, fiber: 3, gi: 15,
    glutenFree: true, diet: "vegetarian", timeMin: 15,
    goals: ["muscle_gain", "protein_rich", "visceral_fat"],
    hue: "bg-[#F3EAF8]",
    ingredients: [
      "100 g crumbled paneer",
      "½ onion, 1 tomato, capsicum (¼ cup)",
      "1 tsp oil, cumin, turmeric, chilli, salt",
      "Coriander, lemon",
    ],
    steps: [
      "Temper cumin in oil; brown the onion.",
      "Add tomato-capsicum; cook 3 min to masala.",
      "Fold in paneer crumbs; warm through 2 min — don't fry hard.",
      "Finish with coriander and lemon; eat as-is or roll in a roti.",
    ],
    tip: "Add paneer off the high heat — overcooking turns it chalky.",
  },
  {
    id: "veg_daliya",
    region: "North India",
    name: "Vegetable Daliya Upma",
    emoji: "🥣",
    meal: ["breakfast", "lunch", "dinner"],
    kcal: 320, protein: 11, carbs: 52, fat: 7, fiber: 9, gi: 55,
    glutenFree: false, diet: "vegetarian", timeMin: 25,
    goals: ["weight_loss", "optimal_health"],
    hue: "bg-[#FBF3E2]",
    ingredients: [
      "55 g broken wheat (daliya)",
      "1 cup mixed vegetables",
      "1 tsp oil, mustard, curry leaves, ginger",
      "Salt, lemon, coriander",
    ],
    steps: [
      "Dry-roast daliya 2–3 min till fragrant.",
      "Temper spices; sauté veggies 3 min.",
      "Add 1.75 cups water + salt; boil and stir in daliya.",
      "Cover on low 10–12 min till soft; fluff with lemon.",
    ],
    tip: "Daliya's coarser crunch digests slowly — a filling, high-fibre comfort bowl.",
  },
  {
    id: "moong_khichdi",
    region: "Pan-India",
    name: "Classic Moong Dal Khichdi",
    emoji: "🍲",
    meal: ["lunch", "dinner"],
    kcal: 350, protein: 15, carbs: 52, fat: 8, fiber: 7, gi: 55,
    glutenFree: true, diet: "vegetarian", timeMin: 30,
    goals: ["optimal_health", "weight_gain", "muscle_gain"],
    hue: "bg-[#EAF4E2]",
    ingredients: [
      "60 g rice + 40 g moong dal",
      "1 tsp ghee, cumin, hing, turmeric",
      "Ginger, salt, 2.5 cups water",
      "Lemon and papad to serve (baked)",
    ],
    steps: [
      "Rinse rice and dal together; soak 15 min.",
      "Temper cumin and hing in ghee; add turmeric and ginger.",
      "Add rice-dal, salt, water; pressure-cook 3–4 whistles till soft.",
      "Stir, rest 5 min; serve with curd or kadhi.",
    ],
    tip: "The original gut-rest food — soft, balanced and easy on digestion.",
  },
  {
    id: "chole_brown_rice",
    region: "Punjab",
    name: "Amritsari-style Chole + Brown Rice",
    emoji: "🍛",
    meal: ["lunch"],
    kcal: 460, protein: 17, carbs: 68, fat: 10, fiber: 14, gi: 52,
    glutenFree: true, diet: "vegan", timeMin: 40,
    goals: ["optimal_health", "muscle_gain", "weight_gain"],
    hue: "bg-[#EAF4E2]",
    ingredients: [
      "70 g dry kabuli chana (or 180 g canned, drained)",
      "Onion-tomato masala, ginger-garlic",
      "Chole masala 1 tsp, anardana or amchur",
      "1 tsp oil, salt; 90 g cooked brown rice",
    ],
    steps: [
      "Pressure-cook soaked chana till tender (or use canned, rinsed).",
      "Build dark onion masala in oil; add ginger-garlic and tomato.",
      "Spice, add chana with cooking liquid; simmer 15 min, lightly mash a few.",
      "Serve over brown rice with onion rings and lemon.",
    ],
    tip: "Mashing a few chana thickens the gravy naturally — no cream needed.",
  },
  {
    id: "palak_dal_jowar",
    region: "North India",
    name: "Palak Dal Tadka + Jowar Roti",
    emoji: "🥬",
    meal: ["lunch", "dinner"],
    kcal: 380, protein: 17, carbs: 48, fat: 11, fiber: 11, gi: 50,
    glutenFree: true, diet: "vegan", timeMin: 30,
    goals: ["weight_loss", "visceral_fat", "optimal_health"],
    hue: "bg-[#E4F6EE]",
    ingredients: [
      "55 g toor/moong dal",
      "1.5 cups chopped spinach",
      "1 tsp oil, garlic, cumin, red chilli, tomato",
      "1 jowar (sorghum) roti",
    ],
    steps: [
      "Cook dal with turmeric till soft; whisk smooth.",
      "Wilt spinach into the dal 2 min; salt.",
      "Tadka: garlic + cumin + chilli in oil; pour sizzling over the dal.",
      "Serve with warm jowar roti and lemon.",
    ],
    tip: "Iron from palak + vitamin C from lemon/tomato boosts absorption 3×.",
  },
  {
    id: "lauki_chana_dal",
    region: "North India",
    name: "Lauki-Chana Dal",
    emoji: "🎃",
    meal: ["lunch", "dinner"],
    kcal: 300, protein: 14, carbs: 42, fat: 7, fiber: 9, gi: 45,
    glutenFree: true, diet: "vegan", timeMin: 30,
    goals: ["weight_loss", "visceral_fat", "optimal_health"],
    hue: "bg-[#EAF4E2]",
    ingredients: [
      "50 g chana dal, soaked 1 h",
      "1.5 cups diced lauki (bottle gourd)",
      "1 tsp oil, cumin, hing, green chilli",
      "Turmeric, salt, coriander",
    ],
    steps: [
      "Pressure-cook dal + lauki + turmeric with 1.5 cups water (2–3 whistles).",
      "Temper cumin, hing, chilli in oil; pour into the dal.",
      "Simmer 5 min to marry flavours; salt to taste.",
      "Garnish with coriander; serve with rice or roti.",
    ],
    tip: "Lauki is 92% water and very low GI — volume eating without calories.",
  },
  {
    id: "baingan_bharta",
    region: "Punjab",
    name: "Smoky Baingan Bharta + Bajra Roti",
    emoji: "🍆",
    meal: ["lunch", "dinner"],
    kcal: 330, protein: 9, carbs: 36, fat: 16, fiber: 10, gi: 45,
    glutenFree: true, diet: "vegan", timeMin: 35,
    goals: ["weight_loss", "visceral_fat", "optimal_health"],
    hue: "bg-[#FCEFD9]",
    ingredients: [
      "1 large baingan (eggplant, ~250 g)",
      "1 onion, 2 tomatoes, ginger-garlic",
      "1.5 tsp mustard oil, cumin, chilli, garam masala",
      "1 bajra roti",
    ],
    steps: [
      "Roast baingan over flame/oven till collapsed; peel and mash.",
      "Sauté cumin, onion, ginger-garlic in mustard oil till deep gold.",
      "Add tomatoes + spices; cook to masala, then fold in the mash.",
      "Roast bharta 5 min on medium for smokiness; serve with bajra roti.",
    ],
    tip: "Mustard oil must smoke slightly first — raw it bites, smoked it's magic.",
  },
  {
    id: "tandoori_chicken_salad",
    region: "Punjab",
    name: "Oven Tandoori Chicken + Salad",
    emoji: "🍗",
    meal: ["lunch", "dinner"],
    kcal: 380, protein: 38, carbs: 10, fat: 20, fiber: 4, gi: 15,
    glutenFree: true, diet: "nonveg", timeMin: 40,
    goals: ["muscle_gain", "visceral_fat", "protein_rich", "weight_loss"],
    hue: "bg-[#FCEFD9]",
    ingredients: [
      "180 g chicken (thigh boneless or breast)",
      "3 tbsp thick curd, 1 tsp tandoori masala",
      "Ginger-garlic, lemon, kashmiri chilli",
      "Cucumber-onion salad with chaat masala",
    ],
    steps: [
      "Score the chicken; rub in ginger-garlic, salt, lemon; rest 15 min.",
      "Marinate in spiced curd 30 min (or overnight for depth).",
      "Bake at 200°C 18–22 min, basting once; char 2 min under the broiler.",
      "Rest 5 min; serve over the crunchy salad.",
    ],
    tip: "Kashmiri chilli gives the classic red without the burn.",
  },
  {
    id: "chicken_curry_brown",
    region: "North India",
    name: "Home-style Chicken Curry + Brown Rice",
    emoji: "🍛",
    meal: ["lunch", "dinner"],
    kcal: 470, protein: 34, carbs: 46, fat: 15, fiber: 6, gi: 52,
    glutenFree: true, diet: "nonveg", timeMin: 40,
    goals: ["muscle_gain", "protein_rich", "optimal_health", "weight_gain"],
    hue: "bg-[#FCEFD9]",
    ingredients: [
      "150 g chicken, curry cut",
      "1 onion, 2 tomatoes, ginger-garlic paste",
      "1 tsp oil, coriander powder, garam masala, turmeric",
      "90 g cooked brown rice",
    ],
    steps: [
      "Brown onions well in oil — this is the gravy's backbone.",
      "Add ginger-garlic, tomatoes; cook till oil separates.",
      "Add chicken + dry spices; sear 4 min, then simmer covered 18 min.",
      "Rest 5 min; serve with brown rice and salad.",
    ],
    tip: "If oil separates from the masala, your curry is done building — rice in the chicken.",
  },
  {
    id: "pepper_chicken_dry",
    region: "South India",
    name: "Chettinad-style Pepper Chicken (Dry)",
    emoji: "🌶️",
    meal: ["lunch", "dinner", "snack"],
    kcal: 280, protein: 30, carbs: 12, fat: 13, fiber: 3, gi: 20,
    glutenFree: true, diet: "nonveg", timeMin: 25,
    goals: ["protein_rich", "muscle_gain", "weight_loss", "visceral_fat"],
    hue: "bg-[#FCEFD9]",
    ingredients: [
      "150 g chicken breast, bite-size",
      "1 tsp crushed black pepper, fennel ¼ tsp",
      "Curry leaves, onion, ginger-garlic",
      "1.5 tsp coconut oil, turmeric, salt",
    ],
    steps: [
      "Sear chicken with turmeric + salt; set aside when 80% done.",
      "In the same pan, fry onions, ginger-garlic, curry leaves.",
      "Return chicken; dry-roast with pepper + fennel 4–5 min.",
      "Finish with a final crack of pepper and lemon.",
    ],
    tip: "Crush pepper just before cooking — pre-ground pepper loses its aroma fast.",
  },
  {
    id: "prawn_masala",
    region: "South India",
    name: "Prawn Masala (10-min)",
    emoji: "🦐",
    meal: ["lunch", "dinner"],
    kcal: 320, protein: 28, carbs: 18, fat: 14, fiber: 4, gi: 35,
    glutenFree: true, diet: "nonveg", timeMin: 20,
    goals: ["protein_rich", "muscle_gain", "visceral_fat"],
    hue: "bg-[#FCEFD9]",
    ingredients: [
      "180 g prawns, cleaned",
      "1 onion, 2 tomatoes, ginger-garlic",
      "1.5 tsp oil, chilli, turmeric, garam masala",
      "Curry leaves, coriander, lemon",
    ],
    steps: [
      "Marinate prawns in turmeric, chilli, salt 10 min.",
      "Build quick onion-tomato masala in oil, 6–7 min.",
      "Add prawns; cook exactly 3–4 min till they curl and turn opaque.",
      "Finish with coriander + lemon; serve immediately.",
    ],
    tip: "Prawns go from perfect to rubber in a minute — pull them as soon as they curl.",
  },
  {
    id: "egg_curry_light",
    region: "Pan-India",
    name: "Light Egg Curry (No Coconut)",
    emoji: "🥚",
    meal: ["lunch", "dinner"],
    kcal: 330, protein: 18, carbs: 20, fat: 18, fiber: 4, gi: 35,
    glutenFree: true, diet: "egg", timeMin: 25,
    goals: ["muscle_gain", "protein_rich", "optimal_health"],
    hue: "bg-[#FBF3E2]",
    ingredients: [
      "3 boiled eggs",
      "1 onion, 2 tomatoes, ginger-garlic",
      "1.5 tsp oil, turmeric, chilli, coriander powder",
      "2 tbsp curd whisked (for creaminess)",
    ],
    steps: [
      "Halve boiled eggs; dust with turmeric, sear lightly in oil.",
      "Build onion-tomato masala; blend smooth if you like a silky gravy.",
      "Simmer masala + ½ cup water 6 min; whisk in curd off the heat.",
      "Slide eggs in; warm 2 min. Never boil after adding curd.",
    ],
    tip: "Lightly searing eggs gives them a golden jacket that holds the gravy.",
  },
  {
    id: "soya_keema_roti",
    region: "North India",
    name: "Soya Keema + Phulka",
    emoji: "🌱",
    meal: ["lunch", "dinner"],
    kcal: 400, protein: 28, carbs: 42, fat: 12, fiber: 10, gi: 50,
    glutenFree: false, diet: "vegetarian", timeMin: 30,
    goals: ["muscle_gain", "protein_rich", "weight_loss"],
    hue: "bg-[#EAF4E2]",
    ingredients: [
      "50 g soya granules (rehydrated, squeezed)",
      "1 onion, 2 tomatoes, ginger-garlic",
      "1.5 tsp oil, garam masala, coriander powder",
      "2 phulkas (40 g atta total), peas ¼ cup",
    ],
    steps: [
      "Soak soya in hot water 10 min; drain and squeeze very dry.",
      "Brown onions in oil; add ginger-garlic, tomatoes, spices.",
      "Add soya + peas; cook 6–7 min till keema-textured.",
      "Serve with hot phulkas, onion slices and lemon.",
    ],
    tip: "Squeeze the granules bone-dry or the keema turns soggy.",
  },
  {
    id: "kala_chana_sundal",
    region: "Tamil Nadu",
    name: "Kala Chana Sundal",
    emoji: "🌰",
    meal: ["snack"],
    kcal: 170, protein: 9, carbs: 22, fat: 5, fiber: 8, gi: 30,
    glutenFree: true, diet: "vegan", timeMin: 20,
    goals: ["weight_loss", "visceral_fat", "protein_rich"],
    hue: "bg-[#EAF4E2]",
    ingredients: [
      "60 g cooked kala chana",
      "1 tsp coconut oil, mustard, curry leaves",
      "2 tbsp grated coconut",
      "Asafoetida, green chilli, lemon",
    ],
    steps: [
      "Pressure-cook soaked chana till just tender (not mushy).",
      "Temper mustard, chilli, curry leaves, hing in coconut oil.",
      "Toss in the chana + salt; warm 2 min.",
      "Finish with coconut and lemon; eat warm or at room temperature.",
    ],
    tip: "South India's protein-forward evening snack — better than any biscuit.",
  },
  {
    id: "masala_chaas",
    region: "Pan-India",
    name: "Masala Chaas (Spiced Buttermilk)",
    emoji: "🥛",
    meal: ["snack"],
    kcal: 60, protein: 4, carbs: 6, fat: 2, fiber: 0, gi: 15,
    glutenFree: true, diet: "vegetarian", timeMin: 5,
    goals: ["weight_loss", "visceral_fat", "optimal_health"],
    hue: "bg-[#F3EAF8]",
    ingredients: [
      "200 ml curd + 150 ml chilled water",
      "Roasted cumin powder, black salt",
      "Coriander, curry leaf, green chilli (optional)",
      "Pinch of ginger (fresh grated)",
    ],
    steps: [
      "Whisk curd smooth with water — no lumps.",
      "Season with roasted cumin + black salt.",
      "Crush coriander, curry leaf, chilli lightly; stir in.",
      "Serve cold — the classic Indian cooling drink.",
    ],
    tip: "The 3 pm chaas replaces the 3 pm biscuit — same ritual, 60 calories.",
  },
  {
    id: "makhana_roast",
    region: "North India",
    name: "Roasted Masala Makhana",
    emoji: "🍿",
    meal: ["snack"],
    kcal: 160, protein: 5, carbs: 22, fat: 6, fiber: 3, gi: 35,
    glutenFree: true, diet: "vegetarian", timeMin: 12,
    goals: ["weight_loss", "optimal_health"],
    hue: "bg-[#FBF3E2]",
    ingredients: [
      "25 g (about 1 cup) phool makhana",
      "1 tsp ghee",
      "Roasted cumin, chaat masala, black salt",
      "Pinch of chilli powder",
    ],
    steps: [
      "Roast makhana in dry ghee on low heat 6–8 min till crisp.",
      "Cool 2 min — they crisp up more as they cool.",
      "Toss with ghee and spices.",
      "Store airtight for a 3-day snack stash.",
    ],
    tip: "Test one: if it snaps clean, the batch is done. Chewy means 2 more minutes.",
  },
  {
    id: "fruit_chaat",
    region: "Pan-India",
    name: "Spiced Fruit Chaat",
    emoji: "🍎",
    meal: ["snack", "breakfast"],
    kcal: 140, protein: 2, carbs: 30, fat: 1, fiber: 6, gi: 40,
    glutenFree: true, diet: "vegan", timeMin: 8,
    goals: ["weight_loss", "optimal_health", "visceral_fat"],
    hue: "bg-[#EAF4E2]",
    ingredients: [
      "1 guava or apple, ½ papaya cup",
      "Pomegranate pearls ¼ cup",
      "Chaat masala, black salt, roasted cumin",
      "Lemon, mint leaves",
    ],
    steps: [
      "Chop fruit into bite-size pieces.",
      "Toss with spices and lemon just before eating.",
      "Tear mint over the top.",
      "Chill fruit beforehand for the best contrast.",
    ],
    tip: "Whole fruit's fibre slows the sugar — juice never gets that halo.",
  },
  {
    id: "egg_chaat",
    region: "Pan-India",
    name: "Boiled Egg Chaat",
    emoji: "🥚",
    meal: ["snack"],
    kcal: 180, protein: 12, carbs: 10, fat: 9, fiber: 2, gi: 20,
    glutenFree: true, diet: "egg", timeMin: 10,
    goals: ["weight_loss", "protein_rich", "muscle_gain"],
    hue: "bg-[#FBF3E2]",
    ingredients: [
      "2 boiled eggs, quarters",
      "½ onion, ½ tomato, coriander",
      "Chaat masala, black salt, roasted cumin",
      "Lemon, tamarind chutney 1 tsp (optional)",
    ],
    steps: [
      "Boil eggs 9 min; cool, peel, quarter.",
      "Toss gently with onion, tomato, spices.",
      "Dress with lemon (and tamarind if you like sweet-sour).",
      "Eat immediately — the onions should stay crisp.",
    ],
    tip: "Evening protein is the most skipped meal — this fixes it in 10 minutes.",
  },
  {
    id: "curd_rice_brown",
    region: "Tamil Nadu",
    name: "Brown Rice Curd Rice",
    emoji: "🍚",
    meal: ["lunch"],
    kcal: 340, protein: 11, carbs: 52, fat: 8, fiber: 5, gi: 50,
    glutenFree: true, diet: "vegetarian", timeMin: 15,
    goals: ["optimal_health", "muscle_gain", "weight_gain"],
    hue: "bg-[#F3EAF8]",
    ingredients: [
      "90 g cooked brown rice (cooled)",
      "200 ml curd, 2 tbsp milk",
      "1 tsp oil, mustard, urad dal, ginger, curry leaves",
      "Pomegranate + coriander to top",
    ],
    steps: [
      "Mash warm-ish rice lightly; mix in curd + milk; salt.",
      "Temper mustard, urad, ginger, curry leaves in oil.",
      "Pour the tadka over; fold once.",
      "Top with pomegranate; serve cool.",
    ],
    tip: "Brown rice drops the GI by ~15 points versus white — same comfort, steadier sugar.",
  },
  // ─── Regional collection: Tamil Nadu ───────────────────────────────────────
  {
    id: "idli_sambar",
    region: "Tamil Nadu",
    name: "Steamed Idli (3) + Sambar",
    emoji: "🍥",
    meal: ["breakfast"],
    kcal: 275, protein: 12, carbs: 48, fat: 4, fiber: 6, gi: 62,
    glutenFree: true, diet: "vegetarian", timeMin: 20,
    goals: ["weight_loss", "visceral_fat", "optimal_health"],
    hue: "bg-[#E4F6EE]",
    ingredients: [
      "3 idlis from fermented rice-urad batter (~150 g)",
      "1 cup sambar (toor dal + drumstick, carrot, shallots)",
      "1 tsp gingelly oil, mustard, curry leaves",
      "Coriander to finish",
    ],
    steps: [
      "Steam idlis 10 min in a greased idli plate until springy.",
      "Simmer sambar: cooked toor dal, tamarind, sambar powder, veggies.",
      "Temper mustard + curry leaves in gingelly oil; pour over sambar.",
      "Serve idlis dunked or alongside hot sambar.",
    ],
    tip: "Fermentation lowers idli's GI and adds B12-friendly bacteria — always use well-risen batter.",
  },
  {
    id: "rasam",
    region: "Tamil Nadu",
    name: "Tomato-Garlic Rasam",
    emoji: "🍲",
    meal: ["lunch", "dinner"],
    kcal: 95, protein: 4, carbs: 13, fat: 3, fiber: 3, gi: 30,
    glutenFree: true, diet: "vegan", timeMin: 15,
    goals: ["weight_loss", "visceral_fat", "optimal_health"],
    hue: "bg-[#FCEFD9]",
    ingredients: [
      "2 ripe tomatoes, crushed by hand",
      "6 garlic cloves + ½ tsp cumin, pounded",
      "2 tbsp cooked toor dal water (thin)",
      "Tamarind extract, rasam powder, turmeric",
      "Mustard, curry leaves, ½ tsp oil",
    ],
    steps: [
      "Simmer tamarind + tomato + turmeric 6–7 min.",
      "Add pounded garlic-cumin, rasam powder, salt, dal water.",
      "Heat till frothy just below a boil — never hard-boil.",
      "Finish with mustard-curry leaf tempering and coriander.",
    ],
    tip: "Rasam should never boil — 'aimbu kachchal' kills the aroma. Froth, don't roll.",
  },
  {
    id: "puliogare",
    region: "Tamil Nadu",
    name: "Puliyodharai (Tamarind Rice)",
    emoji: "🍚",
    meal: ["lunch", "dinner"],
    kcal: 385, protein: 8, carbs: 64, fat: 11, fiber: 6, gi: 52,
    glutenFree: true, diet: "vegan", timeMin: 25,
    goals: ["muscle_gain", "weight_gain", "optimal_health"],
    hue: "bg-[#FBF3E2]",
    ingredients: [
      "150 g cooked brown rice, cooled",
      "Lemon-sized tamarind, soaked & pulped",
      "2 tsp puliyodharai (or sambar) powder",
      "Peanuts 1 tbsp + chana & urad dal 1 tsp each",
      "1.5 tsp gingelly oil, mustard, curry leaves, turmeric",
    ],
    steps: [
      "Cook tamarind pulp with powder, turmeric & salt into a thick paste.",
      "Fry peanuts and dals in oil till golden; add mustard + curry leaves.",
      "Fold the tamarind paste through the rice, grain by grain.",
      "Rest 10 min before eating — the flavour deepens.",
    ],
    tip: "Gingelly (sesame) oil is non-negotiable here — it IS the temple-kitchen flavour.",
  },
  {
    id: "beans_usili",
    region: "Tamil Nadu",
    name: "Beans Usili (Lentil-Crumbled Beans)",
    emoji: "🫛",
    meal: ["lunch", "dinner"],
    kcal: 215, protein: 11, carbs: 20, fat: 10, fiber: 7, gi: 15,
    glutenFree: true, diet: "vegan", timeMin: 25,
    goals: ["muscle_gain", "protein_rich", "weight_loss", "visceral_fat", "optimal_health"],
    hue: "bg-[#EAF4E2]",
    ingredients: [
      "150 g French beans, finely chopped",
      "50 g toor dal, soaked 1 hr, coarse-ground with 2 red chillies",
      "1.5 tsp oil, mustard, urad dal, curry leaves",
      "Salt, pinch of asafoetida",
    ],
    steps: [
      "Steam the coarse dal paste 10 min till just cooked; crumble.",
      "Sauté beans in oil with tempering till bright green.",
      "Add crumbled dal, salt; toss 3–4 min on high.",
      "Finish with curry leaves; serve warm as a side.",
    ],
    tip: "Chidambaram-style usili turns a side dish into 11 g of legume protein.",
  },
  {
    id: "keerai_poriyal",
    region: "Tamil Nadu",
    name: "Keerai Poriyal (Greens + Coconut)",
    emoji: "🥬",
    meal: ["lunch", "dinner"],
    kcal: 165, protein: 5, carbs: 12, fat: 11, fiber: 6, gi: 15,
    glutenFree: true, diet: "vegan", timeMin: 15,
    goals: ["weight_loss", "visceral_fat", "optimal_health"],
    hue: "bg-[#EAF4E2]",
    ingredients: [
      "250 g amaranth / mulai keerai, chopped",
      "1.5 tbsp grated coconut",
      "1 tsp oil, mustard, urad dal, 1 red chilli",
      "1 garlic clove, salt",
    ],
    steps: [
      "Wilt greens with a sprinkle of water, 4–5 min — no boiling.",
      "Add salt; cook off the water completely.",
      "Temper mustard, urad, chilli, garlic in oil; toss in.",
      "Fold in coconut off the heat; serve immediately.",
    ],
    tip: "Iron-rich keerai + lemon on the side triples non-heme iron absorption.",
  },
  {
    id: "millet_uttapam",
    region: "Tamil Nadu",
    name: "Vegetable Millet Uttapam",
    emoji: "🫓",
    meal: ["breakfast", "dinner"],
    kcal: 315, protein: 11, carbs: 50, fat: 8, fiber: 6, gi: 55,
    glutenFree: true, diet: "vegetarian", timeMin: 25,
    goals: ["muscle_gain", "weight_loss", "optimal_health"],
    hue: "bg-[#FCEFD9]",
    ingredients: [
      "Batter: 80 g millet + 20 g urad, fermented (or ready millet batter)",
      "Onion, tomato, capsicum, coriander — finely chopped",
      "1 tsp oil per uttapam, green chilli",
      "Idli-podi or chutney to serve",
    ],
    steps: [
      "Pour a thick uttapam on a hot greased tawa.",
      "Scatter veggies + chilli on top; press gently.",
      "Cook covered 3 min; flip for 1 min for even cooking.",
      "Serve with chutney or podi-oil.",
    ],
    tip: "Thick batter + covered cooking gives a soft middle with a crisp lace base.",
  },
  {
    id: "chettinad_chicken",
    region: "Tamil Nadu",
    name: "Chettinad Chicken + Brown Rice",
    emoji: "🍗",
    meal: ["lunch", "dinner"],
    kcal: 470, protein: 38, carbs: 28, fat: 23, fiber: 5, gi: 50,
    glutenFree: true, diet: "nonveg", timeMin: 40,
    goals: ["muscle_gain", "protein_rich", "visceral_fat"],
    hue: "bg-[#FCEFD9]",
    ingredients: [
      "150 g chicken, curd-marinated 20 min",
      "Roast & grind: pepper, fennel, cumin, star anise, kalpasi, coconut 1 tbsp",
      "Onion, tomato, ginger-garlic paste",
      "1.5 tsp gingelly oil, curry leaves",
    ],
    steps: [
      "Dry-roast whole spices + coconut; grind to a coarse masala.",
      "Sauté onions, ginger-garlic; cook tomatoes till pulpy.",
      "Add chicken; sear 5 min, then simmer covered 15 min.",
      "Stir in the ground masala; cook 5 min to finish.",
    ],
    tip: "Kalpasi (stone flower) is the secret Chettinad perfume — skip only if truly unavailable.",
  },
  {
    id: "cabbage_kootu",
    region: "Tamil Nadu",
    name: "Cabbage Kootu (Dal-Coconut Stew)",
    emoji: "🥣",
    meal: ["lunch", "dinner"],
    kcal: 230, protein: 9, carbs: 26, fat: 10, fiber: 8, gi: 45,
    glutenFree: true, diet: "vegan", timeMin: 30,
    goals: ["weight_loss", "visceral_fat", "optimal_health"],
    hue: "bg-[#EAF4E2]",
    ingredients: [
      "200 g cabbage, chopped",
      "40 g moong dal (or chana dal)",
      "2 tbsp coconut + 1 tsp cumin, ground",
      "1 tsp oil, mustard, urad, curry leaves, turmeric",
    ],
    steps: [
      "Pressure-cook dal + cabbage + turmeric 2 whistles.",
      "Add coconut-cumin paste + salt; simmer 5 min to thicken.",
      "Temper mustard, urad, curry leaves; pour over.",
      "Serve with brown rice or as a side with rasam rice.",
    ],
    tip: "Cabbage + dal = volume + protein for under 250 kcal — a weight-loss workhorse.",
  },
  // ─── Regional collection: Kerala ───────────────────────────────────────────
  {
    id: "appam_stew",
    region: "Kerala",
    name: "Appam (2) + Vegetable Stew",
    emoji: "🥘",
    meal: ["breakfast", "dinner"],
    kcal: 380, protein: 9, carbs: 54, fat: 14, fiber: 5, gi: 55,
    glutenFree: true, diet: "vegetarian", timeMin: 40,
    goals: ["muscle_gain", "weight_gain", "optimal_health"],
    hue: "bg-[#F3EAF8]",
    ingredients: [
      "Batter: 100 g raw rice + 20 g coconut, ground & fermented",
      "Stew: mixed veg (carrot, beans, potato, peas) 150 g",
      "Thin + thick coconut milk 200 ml",
      "Whole spices: cardamom, clove, cinnamon, ginger, green chilli",
      "1 tsp coconut oil, curry leaves",
    ],
    steps: [
      "Swirl appam batter in an appachatti till lacy rims form; cover 2 min.",
      "For stew: sweat ginger, chillies & whole spices in coconut oil.",
      "Add veggies + thin coconut milk; cook till just tender.",
      "Pour in thick coconut milk; one gentle simmer, done.",
    ],
    tip: "Never boil after adding thick coconut milk — it splits. Two minutes, off the flame.",
  },
  {
    id: "puttu_kadala",
    region: "Kerala",
    name: "Puttu + Kadala Curry",
    emoji: "🥥",
    meal: ["breakfast"],
    kcal: 410, protein: 16, carbs: 60, fat: 12, fiber: 11, gi: 48,
    glutenFree: true, diet: "vegan", timeMin: 40,
    goals: ["muscle_gain", "weight_loss", "optimal_health", "weight_gain"],
    hue: "bg-[#FBF3E2]",
    ingredients: [
      "100 g roasted rice flour, moistened (puttu podi)",
      "½ cup grated coconut, layered",
      "100 g kala chana, soaked overnight",
      "Onion, tomato, ginger, green chilli",
      "Curry leaves, 1 tsp coconut oil, coriander-chilli powders",
    ],
    steps: [
      "Layer wet rice flour + coconut in a puttu kutti; steam 8–10 min.",
      "Pressure-cook soaked chana till soft (3–4 whistles).",
      "Sauté onion-tomato-spices; add chana + cooking liquid; simmer 8 min.",
      "Crush some chana to thicken; finish with coconut oil + curry leaves.",
    ],
    tip: "The chana-rice pairing is a complete protein — Kerala's original balanced breakfast.",
  },
  {
    id: "avial",
    region: "Kerala",
    name: "Avial (Mixed Veg in Coconut-Curd)",
    emoji: "🥗",
    meal: ["lunch", "dinner"],
    kcal: 210, protein: 5, carbs: 18, fat: 13, fiber: 6, gi: 15,
    glutenFree: true, diet: "vegetarian", timeMin: 25,
    goals: ["weight_loss", "visceral_fat", "optimal_health"],
    hue: "bg-[#EAF4E2]",
    ingredients: [
      "250 g mixed veg: yam, drumstick, carrot, beans, ash gourd, raw banana",
      "60 g coconut + 1 tsp cumin + 2 green chillies, coarse-ground",
      "2 tbsp sour curd (or raw mango)",
      "1 tsp coconut oil, curry leaves",
    ],
    steps: [
      "Boil hard veggies (yam, banana) first with salt + turmeric.",
      "Add quick-cooking veg; cook till fork-tender, water mostly gone.",
      "Stir in coconut paste; simmer 3 min; switch off.",
      "Mix in curd + coconut oil + curry leaves. Never re-boil.",
    ],
    tip: "Avial uses whatever's fresh — 7+ veggies is tradition, and each adds its own fibre.",
  },
  {
    id: "kerala_fish_curry",
    region: "Kerala",
    name: "Kerala Red Fish Curry (Meen Curry)",
    emoji: "🐟",
    meal: ["lunch", "dinner"],
    kcal: 330, protein: 33, carbs: 11, fat: 17, fiber: 3, gi: 15,
    glutenFree: true, diet: "nonveg", timeMin: 30,
    goals: ["muscle_gain", "protein_rich", "weight_loss", "visceral_fat"],
    hue: "bg-[#FCEFD9]",
    ingredients: [
      "150 g firm fish steaks (seer fish / kingfish / sardine)",
      "Kudampuli (malabar tamarind) 2 pieces, soaked",
      "Shallots, ginger, garlic, green chilli",
      "Kashmiri chilli + coriander powder, turmeric",
      "1.5 tsp coconut oil, curry leaves",
    ],
    steps: [
      "Sauté shallots, ginger, garlic, curry leaves in coconut oil.",
      "Bloom chilli-coriander powders low; add kudampuli + 200 ml water.",
      "Slip in fish; simmer uncovered 10–12 min, spooning over.",
      "Rest 30 min if you can — day-old meen curry is famously better.",
    ],
    tip: "No coconut milk in true meen curry — kudampuli's smoke-sourness is the signature.",
  },
  {
    id: "fish_moilee",
    region: "Kerala",
    name: "Fish Moilee (Coconut Milk Fish)",
    emoji: "🐟",
    meal: ["lunch", "dinner"],
    kcal: 380, protein: 31, carbs: 10, fat: 24, fiber: 2, gi: 15,
    glutenFree: true, diet: "nonveg", timeMin: 30,
    goals: ["muscle_gain", "protein_rich", "weight_gain"],
    hue: "bg-[#F3EAF8]",
    ingredients: [
      "150 g fish fillets (seer fish / pomfret)",
      "Thick coconut milk 100 ml + thin 150 ml",
      "Onion, ginger, green chilli, whole spices",
      "Turmeric, 1.5 tsp coconut oil, curry leaves",
    ],
    steps: [
      "Fry fish lightly salted-turmeric; keep aside.",
      "Simmer onions-ginger-chilli in thin coconut milk 8 min.",
      "Return fish; poach gently 6 min on low.",
      "Add thick coconut milk off-flame; swirl once; rest before serving.",
    ],
    tip: "Mild moilee is the classic intro to fish curry — the poaching keeps protein ultra-tender.",
  },
  {
    id: "erissery",
    region: "Kerala",
    name: "Pumpkin & Cowpea Erissery",
    emoji: "🎃",
    meal: ["lunch", "dinner"],
    kcal: 250, protein: 9, carbs: 31, fat: 10, fiber: 8, gi: 45,
    glutenFree: true, diet: "vegan", timeMin: 35,
    goals: ["weight_loss", "optimal_health"],
    hue: "bg-[#FBF3E2]",
    ingredients: [
      "250 g yellow pumpkin, cubed",
      "50 g cowpeas (vanpayar), soaked 4 hr",
      "50 g coconut (grind ½, roast ½ with cumin)",
      "1 tsp coconut oil, mustard, curry leaves, turmeric",
    ],
    steps: [
      "Pressure-cook cowpeas till soft; boil pumpkin separately till just done.",
      "Coarse-grind half the coconut with cumin, garlic, chilli.",
      "Combine all + paste; simmer 5 min to a thick curry.",
      "Top with roasted coconut shaving + mustard tempering.",
    ],
    tip: "The roasted-coconut topping is the Onam-sadya magic — don't skip the golden finish.",
  },
  {
    id: "idiyappam_kurma",
    region: "Kerala",
    name: "Idiyappam + Veg Kurma",
    emoji: "🍜",
    meal: ["breakfast", "dinner"],
    kcal: 390, protein: 10, carbs: 60, fat: 12, fiber: 6, gi: 55,
    glutenFree: true, diet: "vegetarian", timeMin: 40,
    goals: ["muscle_gain", "weight_gain", "optimal_health"],
    hue: "bg-[#F3EAF8]",
    ingredients: [
      "100 g roasted rice flour (idiyappam flour), hot water",
      "Kurma: mixed veg 150 g + 40 g soaked cashew-free coconut paste",
      "Whole spices: cinnamon, clove, cardamom, fennel",
      "1 tsp coconut oil, ginger, green chilli, curry leaves",
    ],
    steps: [
      "Knead flour with hot water; press sevai into idli plates; steam 8 min.",
      "Sauté ginger, chilli, spices; add veg + water; cook till tender.",
      "Stir in coconut paste; simmer 5 min till silky.",
      "Serve string hoppers soaked in kurma.",
    ],
    tip: "Hot water (not warm) is what keeps idiyappam dough from cracking.",
  },
  // ─── Regional collection: Karnataka ────────────────────────────────────────
  {
    id: "bisi_bele_bath",
    region: "Karnataka",
    name: "Millet Bisi Bele Bath",
    emoji: "🍛",
    meal: ["lunch"],
    kcal: 410, protein: 14, carbs: 62, fat: 12, fiber: 10, gi: 52,
    glutenFree: true, diet: "vegetarian", timeMin: 40,
    goals: ["muscle_gain", "weight_gain", "optimal_health"],
    hue: "bg-[#FCEFD9]",
    ingredients: [
      "70 g little/foxtail millet + 40 g toor dal",
      "Mixed veg: beans, carrot, peas, capsicum 120 g",
      "Bisi bele powder 2 tsp + tamarind + jaggery pinch",
      "1.5 tsp ghee, mustard, cashews optional, curry leaves",
    ],
    steps: [
      "Pressure-cook millet + dal + veg with turmeric, 3 whistles.",
      "Mash lightly; stir in tamarind, bisi bele powder, salt; simmer 8 min.",
      "Temper mustard + curry leaves in ghee; fold through.",
      "Serve hot with boondi or papad for the full Bengaluru feel.",
    ],
    tip: "Millets swap in for rice to cut the GI by ~10 points — same comfort, better numbers.",
  },
  {
    id: "ragi_mudde",
    region: "Karnataka",
    name: "Ragi Mudde (2) + Sambar",
    emoji: "🟤",
    meal: ["lunch", "dinner"],
    kcal: 390, protein: 14, carbs: 68, fat: 7, fiber: 12, gi: 50,
    glutenFree: true, diet: "vegan", timeMin: 30,
    goals: ["weight_loss", "visceral_fat", "optimal_health"],
    hue: "bg-[#FBF3E2]",
    ingredients: [
      "100 g ragi (finger millet) flour",
      "250 ml water + pinch salt",
      "1 cup sambar or bassaru (greens-dal gravy)",
      "1 tsp oil for the pot",
    ],
    steps: [
      "Boil water; stir in 2 tbsp flour to make a slurry (avoids lumps).",
      "On low, add remaining flour stirring hard till a thick ball forms.",
      "Cook covered 5 min; shape hot balls with a wet hand.",
      "Serve with sambar — the traditional swallow-and-savoury pairing.",
    ],
    tip: "Ragi mudde keeps farmers full for hours — 12 g fibre and calcium most grains can't match.",
  },
  {
    id: "neer_dosa",
    region: "Karnataka",
    name: "Neer Dosa + Coconut Chutney",
    emoji: "🥥",
    meal: ["breakfast", "dinner"],
    kcal: 290, protein: 6, carbs: 46, fat: 9, fiber: 4, gi: 58,
    glutenFree: true, diet: "vegetarian", timeMin: 25,
    goals: ["optimal_health"],
    hue: "bg-[#E4F6EE]",
    ingredients: [
      "Batter: 100 g raw rice, soaked 4 hr, ground watery-thin with coconut 1 tbsp",
      "Coconut chutney: 40 g coconut, green chilli, ginger",
      "1 tsp oil per dosa, salt",
    ],
    steps: [
      "Make a thin, watery batter — 'neer' means water.",
      "Pour on a hot tawa in a spiral; no spreading needed.",
      "Cook covered 1.5 min — it stays pale, not golden.",
      "Fold twice; serve with fresh coconut chutney.",
    ],
    tip: "Thin batter + no fermentation = instant Mangalorean breakfast in under 30 minutes.",
  },
  {
    id: "akki_roti",
    region: "Karnataka",
    name: "Ragi Akki Roti",
    emoji: "🫓",
    meal: ["breakfast", "lunch"],
    kcal: 310, protein: 9, carbs: 46, fat: 10, fiber: 9, gi: 50,
    glutenFree: true, diet: "vegan", timeMin: 25,
    goals: ["weight_loss", "visceral_fat", "optimal_health"],
    hue: "bg-[#FBF3E2]",
    ingredients: [
      "80 g ragi flour + 20 g rice flour",
      "Onion, carrot, dill/kasuri methi, green chilli — grated",
      "2 tbsp curd (or water for vegan), salt",
      "1.5 tsp oil for cooking",
    ],
    steps: [
      "Knead flours with veggies, curd & water into a soft dough.",
      "Pat 2 rotis directly on a greased tawa or banana leaf.",
      "Cook 3 min per side, pressing edges with a wet hand.",
      "Serve hot with chutney or curd.",
    ],
    tip: "Grated onion releases moisture as it cooks — no extra water needed for soft rotis.",
  },
  // ─── Regional collection: Andhra & Telangana ───────────────────────────────
  {
    id: "pesarattu",
    region: "Andhra & Telangana",
    name: "Pesarattu (Green Gram Dosa)",
    emoji: "🌯",
    meal: ["breakfast"],
    kcal: 325, protein: 17, carbs: 42, fat: 10, fiber: 9, gi: 45,
    glutenFree: true, diet: "vegan", timeMin: 25,
    goals: ["muscle_gain", "protein_rich", "weight_loss", "visceral_fat"],
    hue: "bg-[#EAF4E2]",
    ingredients: [
      "100 g whole green gram, soaked 6 hr",
      "Ginger 1 inch, green chillies, cumin",
      "Onion finely chopped (topping)",
      "1.5 tsp oil, Allam pachadi (ginger chutney) to serve",
    ],
    steps: [
      "Grind soaked moong with ginger, chilli, cumin — no fermentation.",
      "Pour thick dosa on hot tawa; scatter onion; drizzle oil.",
      "Cook 3 min, flip for 1 min for a crisp edge.",
      "Serve with allam pachadi — the fiery Andhra companion.",
    ],
    tip: "Whole moong means protein AND fibre in one dosa — Andhra's original protein pancake.",
  },
  {
    id: "gongura_pappu",
    region: "Andhra & Telangana",
    name: "Gongura Pappu (Sorrel-Leaf Dal)",
    emoji: "🌿",
    meal: ["lunch", "dinner"],
    kcal: 275, protein: 12, carbs: 36, fat: 9, fiber: 8, gi: 40,
    glutenFree: true, diet: "vegan", timeMin: 30,
    goals: ["weight_loss", "muscle_gain", "optimal_health"],
    hue: "bg-[#EAF4E2]",
    ingredients: [
      "60 g toor dal",
      "100 g gongura (sorrel) leaves, plucked",
      "Onion, garlic, green chilli, turmeric",
      "1.5 tsp oil, mustard, urad, red chilli, curry leaves",
    ],
    steps: [
      "Pressure-cook dal + gongura + onion + turmeric, 3 whistles.",
      "Mash; simmer 5 min — sorrel's tang does the seasoning work.",
      "Temper garlic + mustard + urad + red chilli; pour in.",
      "Serve with brown rice and a roasted papad.",
    ],
    tip: "Gongura's iron + vitamin C in the same leaf = naturally well-absorbed iron.",
  },
  {
    id: "andhra_chicken",
    region: "Andhra & Telangana",
    name: "Andhra Kodi Kura (Chicken Curry)",
    emoji: "🍛",
    meal: ["lunch", "dinner"],
    kcal: 460, protein: 36, carbs: 30, fat: 22, fiber: 4, gi: 50,
    glutenFree: true, diet: "nonveg", timeMin: 40,
    goals: ["muscle_gain", "protein_rich"],
    hue: "bg-[#FCEFD9]",
    ingredients: [
      "150 g chicken on the bone",
      "Grind: coconut 1 tbsp + poppy seeds 1 tsp (nut-free: use 2 tbsp coconut)",
      "Onion, ginger-garlic paste, curry leaves",
      "Chilli + coriander powder, garam masala, 1.5 tsp oil",
    ],
    steps: [
      "Sauté onions deep golden; add ginger-garlic + curry leaves.",
      "Add chicken; sear on high 5 min till edges brown.",
      "Add powders + ground paste + 100 ml water; simmer 18 min.",
      "Finish with garam masala; rest 5 min before serving.",
    ],
    tip: "Bone-in chicken adds collagen and flavour — just account for slightly less edible protein.",
  },
  {
    id: "podi_idli",
    region: "Andhra & Telangana",
    name: "Podi Idli (Gunpowder Idli Fry)",
    emoji: "🌶️",
    meal: ["breakfast", "snack"],
    kcal: 255, protein: 8, carbs: 38, fat: 8, fiber: 4, gi: 58,
    glutenFree: true, diet: "vegetarian", timeMin: 15,
    goals: ["weight_loss", "optimal_health"],
    hue: "bg-[#FCEFD9]",
    ingredients: [
      "4 mini idlis (or 2 regular, quartered)",
      "2 tsp idli podi (gunpowder) + 1 tsp gingelly oil",
      "Curry leaves, mustard optional",
    ],
    steps: [
      "Toss idlis with podi until every piece is dusted.",
      "Heat oil; roast idlis 3–4 min till edges crisp.",
      "Sharpen with fried curry leaves; serve hot.",
    ],
    tip: "Gingelly oil + podi = the classic combo; leftover idlis taste better fried than fresh.",
  },
  // ─── Regional collection: Maharashtra ──────────────────────────────────────
  {
    id: "zunka_bhakri",
    region: "Maharashtra",
    name: "Zunka + Jowar Bhakri",
    emoji: "🥘",
    meal: ["lunch", "dinner"],
    kcal: 345, protein: 13, carbs: 44, fat: 13, fiber: 9, gi: 50,
    glutenFree: true, diet: "vegan", timeMin: 35,
    goals: ["weight_loss", "muscle_gain", "optimal_health"],
    hue: "bg-[#FBF3E2]",
    ingredients: [
      "80 g besan (gram flour)",
      "Onion, garlic, green chilli",
      "1.5 tsp oil, mustard, turmeric, curry leaves",
      "Jowar flour 70 g (for 1 bhakri)",
    ],
    steps: [
      "Fry onion-garlic-chilli till golden; add turmeric + water 120 ml.",
      "Rain in besan whisking constantly; cook till it stiffens into zunka.",
      "Knead jowar dough hot; pat bhakri; roast both sides, puff on flame.",
      "Serve zunka crumbled over bhakri with raw onion.",
    ],
    tip: "Zunka sets as it cools — pull it while still glossy for the right crumbly texture.",
  },
  {
    id: "misal_usal",
    region: "Maharashtra",
    name: "Misal Usal (Sprout Curry, Light)",
    emoji: "🌱",
    meal: ["breakfast", "snack"],
    kcal: 315, protein: 15, carbs: 44, fat: 9, fiber: 11, gi: 48,
    glutenFree: true, diet: "vegan", timeMin: 30,
    goals: ["muscle_gain", "weight_loss", "optimal_health"],
    hue: "bg-[#EAF4E2]",
    ingredients: [
      "120 g matki (moth beans), sprouted 2 days",
      "Onion, tomato, ginger-garlic, misal masala 1.5 tsp",
      "Toppings: chopped onion, coriander, lemon",
      "1.5 tsp oil (skip the fried farsan to keep it light)",
    ],
    steps: [
      "Sauté onion-tomato-masala into a thick rassa base.",
      "Add sprouts + 250 ml water; simmer 12 min.",
      "Serve usal, top with onion + coriander + lemon.",
      "Add a small handful of farsan only on workout days.",
    ],
    tip: "Two-day sprouts triple the vitamin C of the dry bean — and cut the GI further.",
  },
  {
    id: "thalipeeth",
    region: "Maharashtra",
    name: "Multi-Grain Thalipeeth",
    emoji: "🫓",
    meal: ["breakfast", "lunch"],
    kcal: 325, protein: 10, carbs: 46, fat: 11, fiber: 8, gi: 52,
    glutenFree: false, diet: "vegetarian", timeMin: 30,
    goals: ["muscle_gain", "optimal_health"],
    hue: "bg-[#FCEFD9]",
    ingredients: [
      "90 g bhajani flour (roasted multi-grain: rice, jowar, bajra, wheat)",
      "Onion, coriander, cumin, chilli, turmeric",
      "2 tbsp curd, salt",
      "1.5 tsp ghee or oil",
    ],
    steps: [
      "Mix flour with veggies, curd, water → soft dough; rest 10 min.",
      "Pat a holey roti directly on a hot greased tawa.",
      "Cook 3 min per side with ghee till charred in spots.",
      "Serve with white butter or curd — the Mumbai way.",
    ],
    tip: "Traditional bhajani contains wheat, so it's not gluten-free — ask for a jowar-only version if needed.",
  },
  // ─── Regional collection: Gujarat ──────────────────────────────────────────
  {
    id: "khaman_dhokla",
    region: "Gujarat",
    name: "Steamed Khaman Dhokla",
    emoji: "🟡",
    meal: ["snack", "breakfast"],
    kcal: 220, protein: 11, carbs: 28, fat: 7, fiber: 5, gi: 50,
    glutenFree: true, diet: "vegetarian", timeMin: 30,
    goals: ["weight_loss", "protein_rich", "optimal_health"],
    hue: "bg-[#FBF3E2]",
    ingredients: [
      "100 g besan (gram flour), curd 2 tbsp",
      "Ginger-green chilli paste, Eno ½ tsp (or ¼ tsp soda)",
      "Tempering: mustard, sesame, curry leaves, sugar pinch",
      "Coriander + coconut to top",
    ],
    steps: [
      "Rest besan-curd-ginger batter 15 min; add Eno just before steaming.",
      "Steam 18 min in a greased plate; cool 5 min; cut squares.",
      "Pour water-lemon-sugar over; then hot mustard-sesame tempering.",
      "Top with coriander + coconut; serve warm.",
    ],
    tip: "Steamed, not fried — dhokla is proof Gujarati snacks can be light and protein-rich.",
  },
  {
    id: "dal_dhokli",
    region: "Gujarat",
    name: "Dal Dhokli (One-Pot meal)",
    emoji: "🍜",
    meal: ["lunch", "dinner"],
    kcal: 370, protein: 14, carbs: 58, fat: 9, fiber: 8, gi: 55,
    glutenFree: false, diet: "vegetarian", timeMin: 45,
    goals: ["muscle_gain", "optimal_health"],
    hue: "bg-[#F3EAF8]",
    ingredients: [
      "80 g toor dal, pressure-cooked",
      "Dhokli: 70 g whole-wheat flour, 1 tbsp besan, ajwain, turmeric",
      "Tamarind + jaggery + dhokli spices (the Gujarati sweet-sour)",
      "1.5 tsp oil, mustard, methi seeds, curry leaves",
    ],
    steps: [
      "Knead a stiff dhokli dough; rest 15 min; roll thick; cut diamonds.",
      "Simmer dal with tamarind, jaggery, spices + 300 ml water.",
      "Drop dhokli in; boil gently 12 min — they thicken the dal.",
      "Finish with tempering; rest 5 min (they drink more gravy).",
    ],
    tip: "Wheat dhokli means gluten — pair with salad instead of rice; it's a full bowl on its own.",
  },
  // ─── Regional collection: Punjab ───────────────────────────────────────────
  {
    id: "sarson_saag_makki",
    region: "Punjab",
    name: "Sarson ka Saag + Makki Roti",
    emoji: "🥬",
    meal: ["lunch", "dinner"],
    kcal: 380, protein: 12, carbs: 42, fat: 18, fiber: 11, gi: 50,
    glutenFree: true, diet: "vegetarian", timeMin: 50,
    goals: ["visceral_fat", "weight_loss", "optimal_health"],
    hue: "bg-[#EAF4E2]",
    ingredients: [
      "300 g mixed greens: sarson, palak, bathua",
      "Makki (corn) flour 70 g for 1 roti",
      "Ginger, garlic, green chilli, onion",
      "1.5 tsp ghee, maize slurry for body",
    ],
    steps: [
      "Pressure-cook greens with ginger-garlic-chilli, 2 whistles.",
      "Blitz coarsely; simmer 10 min with a maize slurry to thicken.",
      "Temper garlic + onion in ghee; fold into the saag.",
      "Pat makki roti on a hot tawa; cook with ghee; pair hot.",
    ],
    tip: "Makki roti is naturally gluten-free, and winter greens deliver vitamin K and iron by the boatload.",
  },
  {
    id: "dal_makhani_light",
    region: "Punjab",
    name: "Dal Makhani (Light)",
    emoji: "🍲",
    meal: ["lunch", "dinner"],
    kcal: 335, protein: 15, carbs: 42, fat: 12, fiber: 10, gi: 40,
    glutenFree: true, diet: "vegetarian", timeMin: 45,
    goals: ["muscle_gain", "protein_rich", "optimal_health"],
    hue: "bg-[#F3EAF8]",
    ingredients: [
      "60 g whole urad (sabut) + 1 tbsp rajma, soaked overnight",
      "Tomato purée, ginger, kasuri methi",
      "2 tbsp milk + 1 tsp butter (instead of cream)",
      "1.5 tsp oil, chilli, garam masala",
    ],
    steps: [
      "Pressure-cook soaked urad + rajma till completely soft, 5–6 whistles.",
      "Simmer with tomato purée, ginger, spices 20 min — stir often.",
      "Add milk + butter; simmer 5 min to a glossy black dal.",
      "Crush kasuri methi on top; rest before serving.",
    ],
    tip: "Slow simmer replaces half the butter — the creamy texture comes from time, not cream.",
  },
  // ─── Regional collection: Rajasthan ────────────────────────────────────────
  {
    id: "bajra_khichdi",
    region: "Rajasthan",
    name: "Bajra Khichdi (Pearl Millet + Moong)",
    emoji: "🥣",
    meal: ["lunch", "dinner"],
    kcal: 360, protein: 13, carbs: 55, fat: 10, fiber: 10, gi: 45,
    glutenFree: true, diet: "vegan", timeMin: 35,
    goals: ["weight_loss", "visceral_fat", "optimal_health"],
    hue: "bg-[#FBF3E2]",
    ingredients: [
      "70 g bajra, soaked overnight, coarsely crushed",
      "50 g moong dal",
      "1.5 tsp ghee (or oil), cumin, hing, ginger",
      "Turmeric, salt, veggies optional",
    ],
    steps: [
      "Temper cumin + hing in ghee; add dal + bajra + 3 cups water.",
      "Pressure-cook 4 whistles till soft and porridge-like.",
      "Adjust to a running khichdi consistency with hot water.",
      "Serve with chaas or lehsun chutney — Marwar style.",
    ],
    tip: "Bajra warms the body — Rajasthan's winter staple with a GI that beats white rice khichdi.",
  },
  {
    id: "laal_maas",
    region: "Rajasthan",
    name: "Laal Maas (Light) + Bajra Roti",
    emoji: "🌶️",
    meal: ["dinner"],
    kcal: 425, protein: 35, carbs: 26, fat: 20, fiber: 6, gi: 45,
    glutenFree: true, diet: "nonveg", timeMin: 45,
    goals: ["muscle_gain", "protein_rich"],
    hue: "bg-[#FCEFD9]",
    ingredients: [
      "150 g mutton (goat) or chicken thigh",
      "Mathania-style red chillies soaked & ground (or Kashmiri + 1 dried red)",
      "Garlic 8 cloves, onion, curd 2 tbsp",
      "1.5 tsp mustard oil, cloves, cardamom",
    ],
    steps: [
      "Sear meat in mustard oil with whole spices till browned.",
      "Add garlic + chilli paste; cook till oil separates.",
      "Whisk curd in on low; simmer covered 30 min (mutton) till tender.",
      "Rest 10 min — laal maas deepens as it sits; serve with bajra roti.",
    ],
    tip: "Mathania chillies give colour + heat without oil-extracting burn — smoke the dish with a clove for the royal finish.",
  },
  // ─── Regional collection: Bengal ───────────────────────────────────────────
  {
    id: "machher_jhol",
    region: "Bengal",
    name: "Bengali Machher Jhol + Brown Rice",
    emoji: "🐟",
    meal: ["lunch", "dinner"],
    kcal: 380, protein: 32, carbs: 34, fat: 13, fiber: 5, gi: 50,
    glutenFree: true, diet: "nonveg", timeMin: 35,
    goals: ["muscle_gain", "protein_rich", "weight_loss"],
    hue: "bg-[#FCEFD9]",
    ingredients: [
      "150 g rohu / bhetki / any firm fish, turmeric-salted",
      "Potato + brinjal + raw papaya, cut long",
      "Panch phoron ½ tsp, ginger paste, turmeric",
      "1.5 tsp mustard oil, coriander",
    ],
    steps: [
      "Light-fry salted fish; set aside.",
      "Temper panch phoron in mustard oil; fry potato-brinjal-papaya.",
      "Add ginger-turmeric + 300 ml water; boil till veg soften.",
      "Slip fish in; simmer 6 min; finish with coriander — a thin jhol, not a curry.",
    ],
    tip: "Mustard oil at smoking point first — raw it bites, smoked it's the Bengali signature.",
  },
  {
    id: "bhaja_muger_dal",
    region: "Bengal",
    name: "Bhaja Muger Dal (Roasted Moong Dal)",
    emoji: "🍲",
    meal: ["lunch", "dinner"],
    kcal: 250, protein: 12, carbs: 33, fat: 8, fiber: 7, gi: 40,
    glutenFree: true, diet: "vegetarian", timeMin: 25,
    goals: ["weight_loss", "muscle_gain", "optimal_health"],
    hue: "bg-[#EAF4E2]",
    ingredients: [
      "70 g moong dal, dry-roasted till nutty",
      "Bay leaf, ginger slivers, green chilli",
      "Vegetables optional: green papaya or carrot",
      "1.5 tsp ghee (or oil), cumin, turmeric",
    ],
    steps: [
      "Roast dal dry till golden and aromatic; wash once.",
      "Temper bay + cumin in ghee; add dal + turmeric + 250 ml water.",
      "Cook till just soft — Bengali dal is looser, not thick.",
      "Finish with ginger slivers + green chilli.",
    ],
    tip: "Roasting the dal first is everything — the nutty bhaja flavour you smell in every Bengali kitchen.",
  },
  // ─── Regional collection: Northeast ────────────────────────────────────────
  {
    id: "naga_bamboo_dal",
    region: "Northeast",
    name: "Naga Bamboo-Shoot Dal",
    emoji: "🎋",
    meal: ["lunch", "dinner"],
    kcal: 235, protein: 11, carbs: 30, fat: 8, fiber: 8, gi: 40,
    glutenFree: true, diet: "vegan", timeMin: 30,
    goals: ["weight_loss", "visceral_fat", "optimal_health"],
    hue: "bg-[#EAF4E2]",
    ingredients: [
      "70 g masoor dal",
      "80 g fermented bamboo shoot (or canned, rinsed)",
      "Ghost chilli (raja mircha) sliver — optional heat",
      "1 tsp oil, ginger, spring onion, turmeric",
    ],
    steps: [
      "Boil dal with turmeric till soft.",
      "Add bamboo shoot + ginger; simmer 8 min to marry flavours.",
      "Naga-style: no tempering oil shower — keep it clean and brothy.",
      "Finish with spring onion + a sliver of ghost chilli if you dare.",
    ],
    tip: "Fermented bamboo adds gut-friendly tang — Northeast cooking barely needs oil.",
  },
];
